In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
train_identity=pd.read_csv('ieee-fraud-detection/train_identity.csv')
train_transaction=pd.read_csv('ieee-fraud-detection/train_transaction.csv')

In [4]:
train_identity.head()

,TransactionID,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987004,0.0,70787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
1,2987008,-5.0,98945.0,NaN,NaN,0.0,-5.0,NaN,NaN,NaN,...,mobile safari 11.0,32.0,1334x750,match_status:1,T,F,F,T,mobile,iOS Device
2,2987010,-5.0,191631.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,Windows
3,2987011,-5.0,221832.0,NaN,NaN,0.0,-6.0,NaN,NaN,NaN,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,NaN
4,2987016,0.0,7460.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,...,chrome 62.0,24.0,1280x800,match_status:2,T,F,T,T,desktop,MacOS

In [5]:

print(train_identity.shape)
print(train_identity.info())
print(train_identity.isnull().sum())
train_identity.head()

(144233, 41)
<class 'pandas.DataFrame'>
RangeIndex: 144233 entries, 0 to 144232
Data columns (total 41 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   TransactionID  144233 non-null  int64
 1   id_01          144233 non-null  float64
 2   id_02          140872 non-null  float64
 3   id_03          66324 non-null   float64
 4   id_04          66324 non-null   float64
 5   id_05          136865 non-null  float64
 6   id_06          136865 non-null  float64
 7   id_07          5155 non-null    float64
 8   id_08          5155 non-null    float64
 9   id_09          74926 non-null   float64
 10  id_10          74926 non-null   float64
 11  id_11          140978 non-null  float64
 12  id_12          144233 non-null  str
 13  id_13          127320 non-null  float64
 14  id_14          80044 non-null   float64
 15  id_15          140985 non-null  str
 16  id_16          129340 non-null  str
 17  id_17          139369 non-null  float64
 18  id_18          45113 non-null   float64
 19  id_19          139318 non-null  float64
 20  id_20          139261 non-null  float64
 21  id_21          5159 non-null    float64
 22  id_22          5169 non-null    float64
 23  id_23          5169 non-null    str
 24  id_24          4747 non-null    float64
 25  id_25          5132 non-null    float64
 26  id_26          5163 non-null    float64
 27  id_27          5169 non-null    str
 28  id_28          140978 non-null  str
 29  id_29          140978 non-null  str
 30  id_30          77565 non-null   str
 31  id_31          140282 non-null  str
 32  id_32          77586 non-null   float64
 33  id_33          73289 non-null   str
 34  id_34          77805 non-null   str
 35  id_35          140985 non-null  str
 36  id_36          140985 non-null  str
 37  id_37          140985 non-null  str
 38  id_38          140985 non-null  str
 39  DeviceType     140810 non-null  str
 40  DeviceInfo     118666 non-null  str
dtypes: float64(23), int64(1), str(17)
memory usage: 45.1 MB
None
TransactionID         0
id_01                 0
id_02              3361
id_03             77909
id_04             77909
id_05              7368
id_06              7368
id_07            139078
id_08            139078
id_09             69307
id_10             69307
id_11              3255
id_12                 0
id_13             16913
id_14             64189
id_15              3248
id_16             14893
id_17              4864
id_18             99120
id_19              4915
id_20              4972
id_21            139074
id_22            139064
id_23            139064
id_24            139486
id_25            139101
id_26            139070
id_27            139064
id_28              3255
id_29              3255
id_30             66668
id_31              3951
id_32             66647
id_33             70944
id_34             66428
id_35              3248
id_36              3248
id_37              3248
id_38              3248
DeviceType         3423
DeviceInfo        25567
dtype: int64

,TransactionID,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987004,0.0,70787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
1,2987008,-5.0,98945.0,NaN,NaN,0.0,-5.0,NaN,NaN,NaN,...,mobile safari 11.0,32.0,1334x750,match_status:1,T,F,F,T,mobile,iOS Device
2,2987010,-5.0,191631.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,Windows
3,2987011,-5.0,221832.0,NaN,NaN,0.0,-6.0,NaN,NaN,NaN,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,NaN
4,2987016,0.0,7460.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,...,chrome 62.0,24.0,1280x800,match_status:2,T,F,T,T,desktop,MacOS

In [6]:

print(train_transaction.shape)
print(train_transaction.info())
print(train_transaction.isnull().sum())
print(train_transaction.columns)
train_transaction.head()

(590540, 394)
<class 'pandas.DataFrame'>
RangeIndex: 590540 entries, 0 to 590539
Columns: 394 entries, TransactionID to V339
dtypes: float64(376), int64(4), str(14)
memory usage: 1.7 GB
None
TransactionID          0
isFraud                0
TransactionDT          0
TransactionAmt         0
ProductCD              0
                   ...
V335              508189
V336              508189
V337              508189
V338              508189
V339              508189
Length: 394, dtype: int64
Index(['TransactionID', 'isFraud', 'TransactionDT', 'TransactionAmt',
       'ProductCD', 'card1', 'card2', 'card3', 'card4', 'card5',
       ...
       'V330', 'V331', 'V332', 'V333', 'V334', 'V335', 'V336', 'V337', 'V338',
       'V339'],
      dtype='str', length=394)

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
import pandas as pd
import numpy as np

# Columns we initially care about
transaction_cols = [
    "TransactionID",
    "isFraud",
    "TransactionDT",
    "TransactionAmt",
    "ProductCD",

    # Payment/card information
    "card1", "card2", "card3", "card4", "card5", "card6",

    # Address information
    "addr1", "addr2",

    # Email information
    "P_emaildomain",
    "R_emaildomain",
]

identity_cols = [
    "TransactionID",
    "DeviceType",
    "DeviceInfo",
] + [f"id_{i:02d}" for i in range(1, 39)]

tx = train_transaction[transaction_cols].copy()

identity = train_identity[identity_cols].copy()

df = tx.merge(
    identity,
    on="TransactionID",
    how="left"
)

print(df.shape)

(590540, 55)

In [8]:
df.head()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,id_29,id_30,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,NotFound,Android 7.0,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T

In [9]:
id_cols = [f"id_{i:02d}" for i in range(1, 39)]

report = []

for col in id_cols:
    s = df[col]

    vc = s.dropna().value_counts()

    report.append({
        "column": col,
        "non_null": s.notna().sum(),
        "missing_pct": round(s.isna().mean() * 100, 2),
        "unique": s.nunique(dropna=True),
        "values_repeated": (vc > 1).sum(),
        "max_frequency": vc.max() if len(vc) else 0
    })

identity_report = pd.DataFrame(report)

print(identity_report.to_string(index=False))

column  non_null  missing_pct  unique  values_repeated  max_frequency
 id_01    144233        75.58      77               54          82170
 id_02    140872        76.15  115655            20835             11
 id_03     66324        88.77      24               22          63903
 id_04     66324        88.77      15               15          65739
 id_05    136865        76.82      93               86          92743
 id_06    136865        76.82     101               99          91325
 id_07      5155        99.13      84               75            409
 id_08      5155        99.13      94               89            500
 id_09     74926        87.31      46               38          70378
 id_10     74926        87.31      62               48          72879
 id_11    140978        76.13     365              267         133162
 id_12    144233        75.58       2                2         123025
 id_13    127320        78.44      54               45          58099
 id_14     80044        86.45      25               22          44121
 id_15    140985        76.13       3                3          67728
 id_16    129340        78.10       2                2          66324
 id_17    139369        76.40     104               90          78631
 id_18     45113        92.36      18               14          25489
 id_19    139318        76.41     522              486          19849
 id_20    139261        76.42     394              314          22311
 id_21      5159        99.13     490              244           2542
 id_22      5169        99.12      25               18           4736
 id_23      5169        99.12       3                3           3489
 id_24      4747        99.20      12               11           2817
 id_25      5132        99.13     341              265           2494
 id_26      5163        99.13      95               80            824
 id_27      5169        99.12       2                2           5155
 id_28    140978        76.13       2                2          76232
 id_29    140978        76.13       2                2          74926
 id_30     77565        86.87      75               74          21155
 id_31    140282        76.25     130              115          22000
 id_32     77586        86.86       4                4          53071
 id_33     73289        87.59     260              175          16874
 id_34     77805        86.82       4                4          60011
 id_35    140985        76.13       2                2          77814
 id_36    140985        76.13       2                2         134066
 id_37    140985        76.13       2                2         110452
 id_38    140985        76.13       2                2          73922

In [10]:
graph_candidates = [
    "card1", "card2", "card3", "card4", "card5", "card6",
    "addr1", "addr2",
    "P_emaildomain", "R_emaildomain",
    "DeviceType", "DeviceInfo"
]

results = []

overall_fraud_rate = df["isFraud"].mean()

for col in graph_candidates:

    temp = df[[col, "isFraud"]].dropna(subset=[col])

    stats = (
        temp.groupby(col)["isFraud"]
        .agg(
            transactions="count",
            frauds="sum",
            fraud_rate="mean"
        )
    )

    repeated = stats[stats["transactions"] >= 2]
    heavily_shared = stats[stats["transactions"] >= 10]

    results.append({
        "column": col,
        "non_null": len(temp),
        "missing_pct": round(df[col].isna().mean() * 100, 2),
        "unique": temp[col].nunique(),

        # Can this attribute connect multiple transactions?
        "repeated_values": len(repeated),
        "values_10plus_tx": len(heavily_shared),
        "max_transactions": int(stats["transactions"].max()),

        # Fraud relationship
        "overall_fraud_rate": round(overall_fraud_rate, 4),
        "max_fraud_rate": round(stats["fraud_rate"].max(), 4),
        "median_fraud_rate": round(stats["fraud_rate"].median(), 4)
    })

graph_report = pd.DataFrame(results)

print(graph_report.to_string(index=False))

       column  non_null  missing_pct  unique  repeated_values  values_10plus_tx  max_transactions  overall_fraud_rate  max_fraud_rate  median_fraud_rate
        card1    590540         0.00   13553            10109              4298             14932               0.035          1.0000             0.0000
        card2    581607         1.51     500              500               500             48935               0.035          0.4068             0.0096
        card3    588975         0.27     114               98                58            521287               0.035          1.0000             0.0120
        card4    588963         0.27       4                4                 4            384767               0.035          0.0773             0.0345
        card5    586281         0.72     119              102                65            296546               0.035          1.0000             0.0000
        card6    588969         0.27       4                4                 4            439938               0.035          0.0668             0.0121
        addr1    524834        11.13     332              209               102             46335               0.035          0.6667             0.0000
        addr2    524834        11.13      74               56                19            520481               0.035          1.0000             0.0000
P_emaildomain    496084        15.99      59               59                59            228355               0.035          0.4079             0.0186
R_emaildomain    137291        76.75      60               60                58             57147               0.035          0.9512             0.0033
   DeviceType    140810        76.16       2                2                 2             85165               0.035          0.1017             0.0834
   DeviceInfo    118666        79.91    1786             1346               513             47722               0.035          1.0000             0.0000

In [11]:
# checking for card 1 column

card_stats = (
    df.groupby("card1")["isFraud"]
      .agg(
          transactions="count",
          frauds="sum",
          fraud_rate="mean"
      )
      .sort_values("transactions", ascending=False)
)

print(card_stats.head(20))

       transactions  frauds  fraud_rate
card1
7919          14932     112    0.007501
9500          14162     528    0.037283
15885         10361     444    0.042853
17188         10344     278    0.026875
15066          7945     313    0.039396
12695          7091     201    0.028346
12544          6773     146    0.021556
6019           6771     294    0.043420
2803           6141      73    0.011887
7585           5334     263    0.049306
10616          5172     202    0.039056
12839          5129      70    0.013648
3154           4614     286    0.061985
2616           4410     314    0.071202
18132          4209      59    0.014018
9633           4158     742    0.178451
15497          3977      43    0.010812
16132          3929      64    0.016289
2884           3873      52    0.013426
16075          3748     182    0.048559

In [12]:
print("\nCards with >= 10 transactions:")
print(
    card_stats[card_stats["transactions"] >= 10]
    .sort_values("fraud_rate", ascending=False)
    .head(20)
)

Cards with >= 10 transactions:
       transactions  frauds  fraud_rate
card1
3342             10      10    1.000000
12473            47      46    0.978723
11716            17      16    0.941176
2675             10       9    0.900000
11331            11       9    0.818182
1469             10       8    0.800000
5853             30      23    0.766667
12422            12       9    0.750000
8801             15      11    0.733333
1676             11       8    0.727273
12023            18      13    0.722222
9499             36      25    0.694444
15525            28      19    0.678571
3939             15      10    0.666667
14015            17      11    0.647059
8820             11       7    0.636364
16475            11       7    0.636364
10175            72      45    0.625000
4347             47      29    0.617021
5912             48      29    0.604167

In [13]:
# checking for device info":
device_stats = (
    df.dropna(subset=["DeviceInfo"])
      .groupby("DeviceInfo")["isFraud"]
      .agg(
          transactions="count",
          frauds="sum",
          fraud_rate="mean"
      )
      .sort_values("transactions", ascending=False)
)

print(device_stats.head(20))

                             transactions  frauds  fraud_rate
DeviceInfo
Windows                             47722    3121    0.065400
iOS Device                          19782    1240    0.062683
MacOS                               12573     278    0.022111
Trident/7.0                          7440      96    0.012903
rv:11.0                              1901      76    0.039979
rv:57.0                               962     103    0.107069
SM-J700M Build/MMB29K                 549      60    0.109290
SM-G610M Build/MMB29K                 461      37    0.080260
SM-G531H Build/LMY48B                 410      33    0.080488
rv:59.0                               362      44    0.121547
SM-G935F Build/NRD90M                 334      31    0.092814
SM-G955U Build/NRD90M                 328      33    0.100610
SM-G532M Build/MMB29T                 316      12    0.037975
ALE-L23 Build/HuaweiALE-L23           312      29    0.092949
SM-G950U Build/NRD90M                 290      16    0.055172
SM-G930V Build/NRD90M                 274       0    0.000000
rv:58.0                               269      49    0.182156
rv:52.0                               256      12    0.046875
SAMSUNG                               235       5    0.021277
SM-G950F Build/NRD90M                 225      34    0.151111

In [14]:
print("\nDevices with >= 10 transactions:")
print(
    device_stats[device_stats["transactions"] >= 10]
    .sort_values("fraud_rate", ascending=False)
    .head(20)
)

Devices with >= 10 transactions:
                                     transactions  frauds  fraud_rate
DeviceInfo
Z813 Build/LMY47O                              11      11    1.000000
Blade L3 Build/KOT49H                          12      12    1.000000
G3123 Build/40.0.A.6.175                       12      12    1.000000
Nexus 6 Build/MOB30M                           11      11    1.000000
VS5012 Build/NRD90M                            34      34    1.000000
SM-N920A Build/MMB29K                          21      21    1.000000
NOKIA                                          10      10    1.000000
Z835 Build/NMF26V                              25      25    1.000000
hi6210sft Build/MRA58K                        190     180    0.947368
TR10CS1 Build/JDQ39                            11      10    0.909091
Lenovo YT3-850M Build/MMB29M                   11      10    0.909091
LG-D320 Build/KOT49I.V10a                      71      61    0.859155
TA-1039 Build/NMF26F                           32      27    0.843750
Moto Z2 Play Build/NPSS26.118-19-11            12      10    0.833333
SM-A300H Build/LRX22G                         203     169    0.832512
TA-1039 Build/N2G47H                           17      14    0.823529
MYA-L03 Build/HUAWEIMYA-L03                    17      14    0.823529
VS425PP Build/LMY47V                           28      23    0.821429
SM-A510M Build/MMB29K                          56      45    0.803571
KFFOWI Build/LVY48F                            65      51    0.784615

In [15]:
device_card_stats = (
    df.dropna(subset=["DeviceInfo", "card1"])
      .groupby("DeviceInfo")
      .agg(
          transactions=("TransactionID", "count"),
          unique_cards=("card1", "nunique"),
          frauds=("isFraud", "sum"),
          fraud_rate=("isFraud", "mean")
      )
)

device_card_stats["cards_per_device"] = (
    device_card_stats["unique_cards"] /
    device_card_stats["transactions"]
)

print(
    device_card_stats[
        device_card_stats["unique_cards"] >= 3
    ]
    .sort_values(
        ["fraud_rate", "unique_cards"],
        ascending=False
    )
    .head(30)
)

                                     transactions  unique_cards  frauds  \
DeviceInfo
VS5012 Build/NRD90M                            34            20      34
SM-N920A Build/MMB29K                          21            15      21
Z835 Build/NMF26V                              25            11      25
NOKIA                                          10             7      10
Blade L3 Build/KOT49H                          12             6      12
Nexus 6 Build/MOB30M                           11             6      11
XT890 Build/9.8.2I-50_SML-25                    8             6       8
A574BL Build/NMF26F                             7             5       7
G3123 Build/40.0.A.6.175                       12             5      12
SM-G850M                                        4             4       4
Z813 Build/LMY47O                              11             4      11
Dream                                           4             3       4
XT1033                                          3             3       3
hi6210sft Build/MRA58K                        190            10     180
TR10CS1 Build/JDQ39                            11             8      10
Lenovo YT3-850M Build/MMB29M                   11             5      10
MotoG3-TE Build/MPDS24.65-33-1-3                9             4       8
LG-D320 Build/KOT49I.V10a                      71            35      61
TA-1039 Build/NMF26F                           32            13      27
Moto Z2 Play Build/NPSS26.118-19-11            12            11      10
ZTE Blade A511 Build/MRA58K                     6             5       5
Alcatel_4060O Build/MMB29M                      6             4       5
Ilium Pad T7X Build/LMY47I                      6             3       5
LT22i Build/6.2.A.1.100                         6             3       5
SM-A300H Build/LRX22G                         203            52     169
MYA-L03 Build/HUAWEIMYA-L03                    17            10      14
TA-1039 Build/N2G47H                           17             7      14
VS425PP Build/LMY47V                           28            20      23
SM-A510M Build/MMB29K                          56            21      45
Alcatel_5044R Build/NRD90M                      5             5       4

                                     fraud_rate  cards_per_device
DeviceInfo
VS5012 Build/NRD90M                    1.000000          0.588235
SM-N920A Build/MMB29K                  1.000000          0.714286
Z835 Build/NMF26V                      1.000000          0.440000
NOKIA                                  1.000000          0.700000
Blade L3 Build/KOT49H                  1.000000          0.500000
Nexus 6 Build/MOB30M                   1.000000          0.545455
XT890 Build/9.8.2I-50_SML-25           1.000000          0.750000
A574BL Build/NMF26F                    1.000000          0.714286
G3123 Build/40.0.A.6.175               1.000000          0.416667
SM-G850M                               1.000000          1.000000
Z813 Build/LMY47O                      1.000000          0.363636
Dream                                  1.000000          0.750000
XT1033                                 1.000000          1.000000
hi6210sft Build/MRA58K                 0.947368          0.052632
TR10CS1 Build/JDQ39                    0.909091          0.727273
Lenovo YT3-850M Build/MMB29M           0.909091          0.454545
MotoG3-TE Build/MPDS24.65-33-1-3       0.888889          0.444444
LG-D320 Build/KOT49I.V10a              0.859155          0.492958
TA-1039 Build/NMF26F                   0.843750          0.406250
Moto Z2 Play Build/NPSS26.118-19-11    0.833333          0.916667
ZTE Blade A511 Build/MRA58K            0.833333          0.833333
Alcatel_4060O Build/MMB29M             0.833333          0.666667
Ilium Pad T7X Build/LMY47I             0.833333          0.500000
LT22i Build/6.2.A.1.100                0.833333          0.500000
SM-A300H Build/LRX22G                  0.832512          0.256158
MYA-L03 Build/HUAWEIMYA-L03            0.823529          0.588235
TA-1039 Build/N2G47H                   0.823529          0.411765
VS425PP Build/LMY47V                   0.821429          0.714286
SM-A510M Build/MMB29K                  0.803571          0.375000
Alcatel_5044R Build/NRD90M             0.800000          1.000000

In [16]:
device_card_stats["risk_score"] = (
    device_card_stats["fraud_rate"]
    * np.log1p(device_card_stats["unique_cards"])
    * np.log1p(device_card_stats["transactions"])
)

In [17]:
print(
    device_card_stats
    .sort_values("risk_score", ascending=False)
    .head(30)
)

                                        transactions  unique_cards  frauds  \
DeviceInfo
SM-A300H Build/LRX22G                            203            52     169
LG-D320 Build/KOT49I.V10a                         71            35      61
hi6210sft Build/MRA58K                           190            10     180
VS5012 Build/NRD90M                               34            20      34
SM-G920P Build/NRD90M                             54            32      39
SM-A510M Build/MMB29K                             56            21      45
KFFOWI Build/LVY48F                               65            20      51
CRO-L03 Build/HUAWEICRO-L03                       68            14      51
SM-N920A Build/MMB29K                             21            15      21
VS425PP Build/LMY47V                              28            20      23
Z835 Build/NMF26V                                 25            11      25
Moto G (5) Plus Build/NPNS25.137-15-11            59            24      35
TA-1039 Build/NMF26F                              32            13      27
SAMSUNG SM-G891A Build/NRD90M                     35            25      22
LG-H650 Build/MRA58K                              50            26      27
SAMSUNG SM-J120H Build/LMY47V                     37            16      25
SM-J500M Build/LMY48B                             88            26      39
Hisense L675 Build/MRA58K                         60            15      32
CHC-U03 Build/HuaweiCHC-U03                       67            26      29
Windows                                        47722          4846    3121
SM-G530H Build/KTU84P                             37            14      22
SAMSUNG SM-G550T1 Build/MMB29K                    17            13      13
MYA-L03 Build/HUAWEIMYA-L03                       17            10      14
F5121 Build/34.3.A.0.252                          52            17      25
SM-J320M Build/LMY47V                            171            23      57
Moto Z2 Play Build/NPSS26.118-19-11               12            11      10
SM-A510M Build/LMY47X                             18             9      14
rv:58.0                                          269           146      49
F5121 Build/34.3.A.0.238                          45            12      23
Blade L3 Build/KOT49H                             12             6      12

                                        fraud_rate  cards_per_device  \
DeviceInfo
SM-A300H Build/LRX22G                     0.832512          0.256158
LG-D320 Build/KOT49I.V10a                 0.859155          0.492958
hi6210sft Build/MRA58K                    0.947368          0.052632
VS5012 Build/NRD90M                       1.000000          0.588235
SM-G920P Build/NRD90M                     0.722222          0.592593
SM-A510M Build/MMB29K                     0.803571          0.375000
KFFOWI Build/LVY48F                       0.784615          0.307692
CRO-L03 Build/HUAWEICRO-L03               0.750000          0.205882
SM-N920A Build/MMB29K                     1.000000          0.714286
VS425PP Build/LMY47V                      0.821429          0.714286
Z835 Build/NMF26V                         1.000000          0.440000
Moto G (5) Plus Build/NPNS25.137-15-11    0.593220          0.406780
TA-1039 Build/NMF26F                      0.843750          0.406250
SAMSUNG SM-G891A Build/NRD90M             0.628571          0.714286
LG-H650 Build/MRA58K                      0.540000          0.520000
SAMSUNG SM-J120H Build/LMY47V             0.675676          0.432432
SM-J500M Build/LMY48B                     0.443182          0.295455
Hisense L675 Build/MRA58K                 0.533333          0.250000
CHC-U03 Build/HuaweiCHC-U03               0.432836          0.388060
Windows                                   0.065400          0.101546
SM-G530H Build/KTU84P                     0.594595          0.378378
SAMSUNG SM-G550T1 Build/MMB29K            0.764706          0.764706
MYA-L03 Build/HUAWEIMYA-L03               0.823529          0.588235
F5121 Build/34.3.A.0.252                  0.480769          0.326923
SM-J320M Build/LMY47V                     0.333333          0.134503
Moto Z2 Play Build/NPSS26.118-19-11       0.833333          0.916667
SM-A510M Build/LMY47X                     0.777778          0.500000
rv:58.0                                   0.182156          0.542751
F5121 Build/34.3.A.0.238                  0.511111          0.266667
Blade L3 Build/KOT49H                     1.000000          0.500000

                                        risk_score
DeviceInfo
SM-A300H Build/LRX22G                    17.578072
LG-D320 Build/KOT49I.V10a                13.166991
hi6210sft Build/MRA58K                   11.931538
VS5012 Build/NRD90M                      10.824337
SM-G920P Build/NRD90M                    10.119540
SM-A510M Build/MMB29K                    10.042427
KFFOWI Build/LVY48F                      10.008160
CRO-L03 Build/HUAWEICRO-L03               8.599630
SM-N920A Build/MMB29K                     8.570189
VS425PP Build/LMY47V                      8.421128
Z835 Build/NMF26V                         8.096066
Moto G (5) Plus Build/NPNS25.137-15-11    7.818162
TA-1039 Build/NMF26F                      7.785690
SAMSUNG SM-G891A Build/NRD90M             7.338855
LG-H650 Build/MRA58K                      6.997674
SAMSUNG SM-J120H Build/LMY47V             6.963552
SM-J500M Build/LMY48B                     6.556349
Hisense L675 Build/MRA58K                 6.078807
CHC-U03 Build/HuaweiCHC-U03               6.019365
Windows                                   5.978986
SM-G530H Build/KTU84P                     5.857212
SAMSUNG SM-G550T1 Build/MMB29K            5.833067
MYA-L03 Build/HUAWEIMYA-L03               5.707725
F5121 Build/34.3.A.0.252                  5.517125
SM-J320M Build/LMY47V                     5.453005
Moto Z2 Play Build/NPSS26.118-19-11       5.311383
SM-A510M Build/LMY47X                     5.273194
rv:58.0                                   5.089178
F5121 Build/34.3.A.0.238                  5.019250
Blade L3 Build/KOT49H                     4.991161

In [18]:
device_network = (
    df.dropna(subset=["DeviceInfo", "card1"])
      .groupby("DeviceInfo")
      .agg(
          transactions=("TransactionID", "count"),
          unique_cards=("card1", "nunique"),
          frauds=("isFraud", "sum"),
          fraud_rate=("isFraud", "mean")
      )
)

# Focus on devices associated with at least 5 cards
interesting_devices = (
    device_network[
        device_network["unique_cards"] >= 5
    ]
    .sort_values(
        ["unique_cards", "fraud_rate"],
        ascending=[False, False]
    )
)

print(interesting_devices.head(50).to_string())

                                     transactions  unique_cards  frauds  fraud_rate
DeviceInfo
Windows                                     47722          4846    3121    0.065400
iOS Device                                  19782          3104    1240    0.062683
MacOS                                       12573          2287     278    0.022111
Trident/7.0                                  7440          1868      96    0.012903
rv:11.0                                      1901           702      76    0.039979
rv:57.0                                       962           422     103    0.107069
SM-G930V Build/NRD90M                         274           167       0    0.000000
SM-G950U Build/NRD90M                         290           164      16    0.055172
SM-G955U Build/NRD90M                         328           163      33    0.100610
rv:59.0                                       362           157      44    0.121547
SAMSUNG                                       235           157       5    0.021277
rv:58.0                                       269           146      49    0.182156
rv:52.0                                       256           140      12    0.046875
SM-N950U Build/NMF26X                         209           133      13    0.062201
rv:48.0                                       178           102       2    0.011236
SM-G935V Build/NRD90M                         137            91       0    0.000000
SM-G935F Build/NRD90M                         334            80      31    0.092814
SM-G950F Build/NRD90M                         225            75      34    0.151111
rv:56.0                                       106            75       8    0.075472
SAMSUNG SM-G950U Build/NRD90M                 104            74       1    0.009615
SM-J700M Build/MMB29K                         549            71      60    0.109290
SAMSUNG SM-G955U Build/NRD90M                  96            70      17    0.177083
SM-G610M Build/MMB29K                         461            65      37    0.080260
SM-G930F Build/NRD90M                         144            63       4    0.027778
SM-G920V Build/NRD90M                          91            63       0    0.000000
SM-G531H Build/LMY48B                         410            55      33    0.080488
Moto                                           77            54       2    0.025974
SM-G930T Build/NRD90M                          76            54       0    0.000000
SM-A300H Build/LRX22G                         203            52     169    0.832512
SAMSUNG-SM-G930A Build/NRD90M                  91            52       0    0.000000
SM-G532M Build/MMB29T                         316            51      12    0.037975
SM-G900V Build/MMB29M                          60            49       0    0.000000
SM-G950U Build/R16NW                           74            48       0    0.000000
SAMSUNG SM-N950U Build/NMF26X                  67            47       4    0.059701
ALE-L23 Build/HuaweiALE-L23                   312            45      29    0.092949
rv:60.0                                        63            43       6    0.095238
SM-G570M Build/MMB29K                         182            42       3    0.016484
Moto Z2 Play Build/NPSS26.118-19-14           129            41      30    0.232558
SM-J730GM Build/NRD90M                        184            41      27    0.146739
Moto G (5) Plus Build/NPN25.137-92            130            41      11    0.084615
Pixel                                          47            41       0    0.000000
SAMSUNG-SM-G935A Build/NRD90M                  43            41       0    0.000000
SM-G955U Build/R16NW                           59            40      13    0.220339
SM-A520F Build/NRD90M                         144            40       0    0.000000
Moto G (4) Build/NPJ25.93-14.7                219            39      40    0.182648
SM-G930P Build/NRD90M                          49            39       0    0.000000
SM-A720F Build/NRD90M                         120            38      22    0.183333
LG-M700 Build/NMF26X                          169            38      29    0.171598
HUAWEI VNS-L23 Build/HUAWEIVNS-L23            112            38      15    0.133929
CAM-L03 Build/HUAWEICAM-L03                   172            38      22    0.127907

In [19]:
suspicious_devices = (
    device_network[
        (device_network["unique_cards"] >= 5) &
        (device_network["transactions"] >= 10)
    ]
    .sort_values(
        ["fraud_rate", "unique_cards"],
        ascending=[False, False]
    )
)

print(
    suspicious_devices.head(50).to_string()
)

                                        transactions  unique_cards  frauds  fraud_rate
DeviceInfo
VS5012 Build/NRD90M                               34            20      34    1.000000
SM-N920A Build/MMB29K                             21            15      21    1.000000
Z835 Build/NMF26V                                 25            11      25    1.000000
NOKIA                                             10             7      10    1.000000
Blade L3 Build/KOT49H                             12             6      12    1.000000
Nexus 6 Build/MOB30M                              11             6      11    1.000000
G3123 Build/40.0.A.6.175                          12             5      12    1.000000
hi6210sft Build/MRA58K                           190            10     180    0.947368
TR10CS1 Build/JDQ39                               11             8      10    0.909091
Lenovo YT3-850M Build/MMB29M                      11             5      10    0.909091
LG-D320 Build/KOT49I.V10a                         71            35      61    0.859155
TA-1039 Build/NMF26F                              32            13      27    0.843750
Moto Z2 Play Build/NPSS26.118-19-11               12            11      10    0.833333
SM-A300H Build/LRX22G                            203            52     169    0.832512
MYA-L03 Build/HUAWEIMYA-L03                       17            10      14    0.823529
TA-1039 Build/N2G47H                              17             7      14    0.823529
VS425PP Build/LMY47V                              28            20      23    0.821429
SM-A510M Build/MMB29K                             56            21      45    0.803571
KFFOWI Build/LVY48F                               65            20      51    0.784615
SM-A510M Build/LMY47X                             18             9      14    0.777778
SAMSUNG SM-T710 Build/NRD90M                      13             9      10    0.769231
SAMSUNG SM-G550T1 Build/MMB29K                    17            13      13    0.764706
CRO-L03 Build/HUAWEICRO-L03                       68            14      51    0.750000
Moto G (4) Build/NPJS25.93-14-8.1-4               12             9       9    0.750000
BLADE V8Q Build/N2G47H                            12             7       9    0.750000
Lenovo TB3-710I Build/LMY47I                      15             5      11    0.733333
SM-G920P Build/NRD90M                             54            32      39    0.722222
Moto G Play Build/NPI26.48-36                     10             9       7    0.700000
SAMSUNG SM-J120H Build/LMY47V                     37            16      25    0.675676
Le X520 Build/IEXCNFN5902303111S                  11             5       7    0.636364
SAMSUNG SM-G891A Build/NRD90M                     35            25      22    0.628571
Windows NT 6.2                                    13             6       8    0.615385
SM-S727VL Build/MMB29M                            15            10       9    0.600000
SM-G530H Build/KTU84P                             37            14      22    0.594595
Moto G (5) Plus Build/NPNS25.137-15-11            59            24      35    0.593220
TA-1038 Build/NMF26O                              24             9      14    0.583333
LG-H650 Build/MRA58K                              50            26      27    0.540000
Hisense L675 Build/MRA58K                         60            15      32    0.533333
moto x4 Build/OPWS27.57-40-6                      32            11      17    0.531250
SM-A720F Build/MMB29K                             17             6       9    0.529412
E6603 Build/32.4.A.1.54                           21             9      11    0.523810
F5121 Build/34.3.A.0.238                          45            12      23    0.511111
SM-G9650 Build/R16NW                              16            11       8    0.500000
SAMSUNG SM-G965U Build/R16NW                      10             8       5    0.500000
SM-J100VPP Build/LMY48B                           12             7       6    0.500000
Moto G (4) Build/NPJS25.93-14-18                  12             5       6    0.500000
F5121 Build/34.3.A.0.252                          52            17      25    0.480769
Moto E (4) Build/NDQS26.69-23-2-3                 11             8       5    0.454545
SAMSUNG SM-T810 Build/NRD90M                      11             7       5    0.454545
FRD-L09 Build/HUAWEIFRD-L09                       20            13       9    0.450000

In [20]:
device_network["network_risk"] = (
    device_network["fraud_rate"]
    * np.log1p(device_network["unique_cards"])
)

print(
    device_network[
        (device_network["unique_cards"] >= 5) &
        (device_network["transactions"] >= 10)
    ]
    .sort_values("network_risk", ascending=False)
    .head(30)
    .to_string()
)

                                        transactions  unique_cards  frauds  fraud_rate  network_risk
DeviceInfo
SM-A300H Build/LRX22G                            203            52     169    0.832512      3.305317
LG-D320 Build/KOT49I.V10a                         71            35      61    0.859155      3.078798
VS5012 Build/NRD90M                               34            20      34    1.000000      3.044522
SM-N920A Build/MMB29K                             21            15      21    1.000000      2.772589
SM-G920P Build/NRD90M                             54            32      39    0.722222      2.525255
VS425PP Build/LMY47V                              28            20      23    0.821429      2.500858
Z835 Build/NMF26V                                 25            11      25    1.000000      2.484907
SM-A510M Build/MMB29K                             56            21      45    0.803571      2.483873
KFFOWI Build/LVY48F                               65            20      51    0.784615      2.388779
hi6210sft Build/MRA58K                           190            10     180    0.947368      2.271690
TA-1039 Build/NMF26F                              32            13      27    0.843750      2.226705
NOKIA                                             10             7      10    1.000000      2.079442
Moto Z2 Play Build/NPSS26.118-19-11               12            11      10    0.833333      2.070756
SAMSUNG SM-G891A Build/NRD90M                     35            25      22    0.628571      2.047946
CRO-L03 Build/HUAWEICRO-L03                       68            14      51    0.750000      2.031038
SAMSUNG SM-G550T1 Build/MMB29K                    17            13      13    0.764706      2.018103
TR10CS1 Build/JDQ39                               11             8      10    0.909091      1.997477
MYA-L03 Build/HUAWEIMYA-L03                       17            10      14    0.823529      1.974737
Nexus 6 Build/MOB30M                              11             6      11    1.000000      1.945910
Blade L3 Build/KOT49H                             12             6      12    1.000000      1.945910
SAMSUNG SM-J120H Build/LMY47V                     37            16      25    0.675676      1.914333
Moto G (5) Plus Build/NPNS25.137-15-11            59            24      35    0.593220      1.909503
G3123 Build/40.0.A.6.175                          12             5      12    1.000000      1.791759
SM-A510M Build/LMY47X                             18             9      14    0.777778      1.790900
LG-H650 Build/MRA58K                              50            26      27    0.540000      1.779752
SAMSUNG SM-T710 Build/NRD90M                      13             9      10    0.769231      1.771219
Moto G (4) Build/NPJS25.93-14-8.1-4               12             9       9    0.750000      1.726939
TA-1039 Build/N2G47H                              17             7      14    0.823529      1.712481
Lenovo YT3-850M Build/MMB29M                      11             5      10    0.909091      1.628872
Moto G Play Build/NPI26.48-36                     10             9       7    0.700000      1.611810

In [21]:
target_device = "SM-A300H Build/LRX22G"

sub = df[
    df["DeviceInfo"] == target_device
][[
    "TransactionID",
    "TransactionDT",
    "isFraud",
    "card1",
    "addr1",
    "P_emaildomain",
    "R_emaildomain"
]].sort_values("TransactionDT")

print("Transactions:", len(sub))
print("Unique cards:", sub["card1"].nunique())
print("Frauds:", sub["isFraud"].sum())
print()

print(sub.head(30).to_string(index=False))

Transactions: 203
Unique cards: 52
Frauds: 169

 TransactionID  TransactionDT  isFraud  card1  addr1 P_emaildomain R_emaildomain
       2994379         238269        1  14276    NaN   hotmail.com   hotmail.com
       2994382         238378        1   8755    NaN   hotmail.com   hotmail.com
       2995976         261555        1  14276    NaN   hotmail.com   hotmail.com
       2995979         261598        1   8755    NaN   hotmail.com   hotmail.com
       3008071         536891        0   9633  161.0     gmail.com     gmail.com
       3044731        1346938        1   2256    NaN   hotmail.com   hotmail.com
       3044737        1346994        1  10553    NaN   hotmail.com   hotmail.com
       3051245        1454305        1   5943    NaN   hotmail.com   hotmail.com
       3051256        1454380        1   5812    NaN   hotmail.com   hotmail.com
       3051264        1454435        1   2256    NaN   hotmail.com   hotmail.com
       3051376        1455570        1   3867    NaN   hotmail.com   hotmail.com
       3051753        1460259        1   8755    NaN   hotmail.com   hotmail.com
       3051760        1460343        1   5943    NaN   hotmail.com   hotmail.com
       3053452        1500249        1   5943    NaN   hotmail.com   hotmail.com
       3053453        1500372        1   3867    NaN   hotmail.com   hotmail.com
       3054677        1536666        1   1976    NaN   hotmail.com   hotmail.com
       3074362        1832944        0  15885    NaN     gmail.com     gmail.com
       3074524        1840207        1  14276    NaN   hotmail.com   hotmail.com
       3074525        1840331        1   8755    NaN   hotmail.com   hotmail.com
       3076001        1875781        1   3887    NaN   hotmail.com   hotmail.com
       3076019        1875859        1   5943    NaN   hotmail.com   hotmail.com
       3079088        1904160        1   1976    NaN   hotmail.com   hotmail.com
       3079353        1907618        1   5943    NaN   hotmail.com   hotmail.com
       3079362        1907708        1   1976    NaN   hotmail.com   hotmail.com
       3079605        1910572        1   7099    NaN   hotmail.com   hotmail.com
       3080324        1931864        1  10369    NaN   hotmail.com   hotmail.com
       3082069        1961356        1  10369    NaN   hotmail.com   hotmail.com
       3087057        2007558        1   1976    NaN   hotmail.com   hotmail.com
       3087210        2017217        1   8755    NaN   hotmail.com   hotmail.com
       3088002        2043821        1   8755    NaN   hotmail.com   hotmail.com

In [22]:
print("\nCards used on this device:")
print(
    sub.groupby("card1")
       .agg(
           transactions=("TransactionID", "count"),
           frauds=("isFraud", "sum"),
           fraud_rate=("isFraud", "mean")
       )
       .sort_values("transactions", ascending=False)
       .to_string()
)

Cards used on this device:
       transactions  frauds  fraud_rate
card1
9026             28      28    1.000000
2256             20      20    1.000000
5812             12      11    0.916667
1976             11      11    1.000000
8755             10      10    1.000000
5943             10      10    1.000000
16136             8       0    0.000000
4504              7       7    1.000000
15885             7       1    0.142857
9633              6       3    0.500000
16095             6       6    1.000000
3154              5       2    0.400000
16346             5       5    1.000000
16062             4       4    1.000000
3867              4       4    1.000000
2801              4       4    1.000000
14276             4       4    1.000000
4461              3       1    0.333333
9917              3       2    0.666667
2650              2       0    0.000000
11201             2       2    1.000000
12778             2       2    1.000000
17188             2       2    1.000000
13832             2       1    0.500000
10054             2       2    1.000000
7949              2       2    1.000000
10086             2       2    1.000000
10369             2       2    1.000000
7099              2       2    1.000000
3887              2       2    1.000000
13335             2       2    1.000000
10568             2       0    0.000000
5535              1       0    0.000000
3901              1       1    1.000000
5009              1       0    0.000000
5365              1       1    1.000000
7585              1       1    1.000000
7205              1       1    1.000000
5595              1       0    0.000000
5629              1       1    1.000000
12839             1       1    1.000000
10876             1       1    1.000000
10553             1       1    1.000000
9065              1       0    0.000000
15890             1       1    1.000000
14543             1       1    1.000000
13413             1       1    1.000000
13346             1       0    0.000000
16578             1       1    1.000000
17147             1       1    1.000000
18282             1       1    1.000000
18301             1       1    1.000000

In [23]:
print("\nAddresses:")
print(
    sub.groupby("addr1")
       .agg(
           transactions=("TransactionID", "count"),
           unique_cards=("card1", "nunique"),
           frauds=("isFraud", "sum")
       )
       .sort_values("transactions", ascending=False)
       .to_string()
)

Addresses:
       transactions  unique_cards  frauds
addr1
161.0             1             1       0

In [24]:
print("\nEmail domains:")
print(
    sub.groupby("P_emaildomain")
       .agg(
           transactions=("TransactionID", "count"),
           unique_cards=("card1", "nunique"),
           frauds=("isFraud", "sum")
       )
       .sort_values("transactions", ascending=False)
       .to_string()
)

Email domains:
               transactions  unique_cards  frauds
P_emaildomain
hotmail.com             159            43     153
gmail.com                36            15      11
outlook.es                3             2       2
anonymous.com             1             1       0
hotmail.es                1             1       0

In [25]:
target_device = "SM-A300H Build/LRX22G"

# Cards associated with our target device
target_cards = (
    df.loc[
        df["DeviceInfo"] == target_device,
        "card1"
    ]
    .dropna()
    .unique()
)

print("Cards connected to target device:", len(target_cards))

# Find every device associated with those cards
card_device_network = (
    df[
        df["card1"].isin(target_cards) &
        df["DeviceInfo"].notna()
    ]
    .groupby("DeviceInfo")
    .agg(
        transactions=("TransactionID", "count"),
        unique_cards=("card1", "nunique"),
        frauds=("isFraud", "sum"),
        fraud_rate=("isFraud", "mean")
    )
    .sort_values(
        ["unique_cards", "transactions"],
        ascending=False
    )
)

print(
    card_device_network.head(50).to_string()
)

Cards connected to target device: 52
                                      transactions  unique_cards  frauds  fraud_rate
DeviceInfo
SM-A300H Build/LRX22G                          203            52     169    0.832512
Windows                                      13391            51    1490    0.111269
Trident/7.0                                   1052            44      24    0.022814
rv:57.0                                        184            35      60    0.326087
SM-G531H Build/LMY48B                          368            33      23    0.062500
SM-G610M Build/MMB29K                          357            32      32    0.089636
rv:11.0                                        238            31       8    0.033613
SM-J700M Build/MMB29K                          435            30      50    0.114943
ALE-L23 Build/HuaweiALE-L23                    270            29      23    0.085185
SM-G532M Build/MMB29T                          270            28      11    0.040741
SM-G935F Build/NRD90M                          244            28      23    0.094262
rv:58.0                                         87            27      22    0.252874
SM-G950F Build/NRD90M                          137            26      16    0.116788
SM-J730GM Build/NRD90M                         159            25      19    0.119497
Moto G (4) Build/NPJ25.93-14.7                 197            24      34    0.172589
Moto G (4) Build/NPJS25.93-14-13               122            24      12    0.098361
rv:59.0                                        121            24      16    0.132231
Moto X Play Build/NPD26.48-24-1                101            24       1    0.009901
MotoG3 Build/MPIS24.65-33.1-2-16                77            24      23    0.298701
Moto G Play Build/MPIS24.241-15.3-7            122            23      17    0.139344
SM-A720F Build/NRD90M                           96            23      12    0.125000
CAM-L03 Build/HUAWEICAM-L03                    148            22      19    0.128378
HUAWEI TAG-L13 Build/HUAWEITAG-L13             101            22      10    0.099010
Moto G (5) Plus Build/NPN25.137-92              86            22       9    0.104651
SM-G570M Build/MMB29K                          156            21       3    0.019231
LG-K410 Build/LRX22G                           126            21       4    0.031746
SM-A520F Build/NRD90M                          113            21       0    0.000000
Moto Z2 Play Build/NPSS26.118-19-14             94            21      22    0.234043
BLADE V8 SE Build/NRD90M                        87            21      20    0.229885
LG-D320 Build/KOT49I.V10a                       55            21      47    0.854545
SM-J510MN Build/MMB29M                         138            20      16    0.115942
Moto E (4) Plus Build/NMA26.42-69              137            20      24    0.175182
SM-J701M Build/NRD90M                          135            20      29    0.214815
LG-M700 Build/NMF26X                           132            20      10    0.075758
PRA-LX3 Build/HUAWEIPRA-LX3                    113            20       0    0.000000
Moto G (4) Build/NPJS25.93-14-10                84            20      16    0.190476
HUAWEI VNS-L23 Build/HUAWEIVNS-L23              83            20      14    0.168675
XT1635-02 Build/NPN26.118-22-2                  78            20      15    0.192308
LG-H500 Build/LRX21Y                            60            20       1    0.016667
Moto G (5) Build/NPPS25.137-15-11               58            20       8    0.137931
SAMSUNG                                         53            20       2    0.037736
HUAWEI VNS-L53 Build/HUAWEIVNS-L53             104            19       3    0.028846
TRT-L53 Build/HUAWEITRT-L53                     97            19      13    0.134021
LG-X230 Build/MRA58K                            88            19       6    0.068182
HTC Desire 10 lifestyle Build/MMB29M            85            19      21    0.247059
LG-K200 Build/MXB48T                            75            19       1    0.013333
LG-X180g Build/LMY47I                           74            19       3    0.040541
Moto C Build/NRD90M.063                         71            19       5    0.070423
F3113 Build/33.3.A.1.97                         63            19       3    0.047619
SM-G530H Build/LRX22G                           58            19       5    0.086207

In [26]:
high_risk_cards = (
    sub.groupby("card1")["isFraud"]
       .agg(
           transactions="count",
           frauds="sum",
           fraud_rate="mean"
       )
)

high_risk_cards = high_risk_cards[
    (high_risk_cards["transactions"] >= 5) &
    (high_risk_cards["fraud_rate"] >= 0.8)
]

print(high_risk_cards)

       transactions  frauds  fraud_rate
card1
1976             11      11    1.000000
2256             20      20    1.000000
4504              7       7    1.000000
5812             12      11    0.916667
5943             10      10    1.000000
8755             10      10    1.000000
9026             28      28    1.000000
16095             6       6    1.000000
16346             5       5    1.000000

In [27]:
cards_to_trace = high_risk_cards.index

card_device_links = (
    df[
        df["card1"].isin(cards_to_trace) &
        df["DeviceInfo"].notna()
    ]
    .groupby(["card1", "DeviceInfo"])
    .agg(
        transactions=("TransactionID", "count"),
        frauds=("isFraud", "sum")
    )
    .sort_values(
        ["card1", "transactions"],
        ascending=[True, False]
    )
)

print(card_device_links.to_string())

                                              transactions  frauds
card1 DeviceInfo
1976  Windows                                          246      34
      Trident/7.0                                       22       0
      Lenovo K33b36 Build/MMB29M                        12       0
      SM-A300H Build/LRX22G                             11      11
      ALE-L23 Build/HuaweiALE-L23                        8       1
      SM-G935F Build/NRD90M                              6       0
      HUAWEI TAG-L13 Build/HUAWEITAG-L13                 5       1
      Moto G (4) Build/NPJS25.93-14-10                   5       4
      BLADE V8 SE Build/NRD90M                           4       2
      LG-H870 Build/NRD90U                               4       0
      LG-X180g Build/LMY47I                              4       2
      Moto Z2 Play Build/NPSS26.118-19-4                 4       0
      SM-A310M Build/LMY47X                              4       0
      Z813 Build/LMY47O                                  4       4
      CAM-L03 Build/HUAWEICAM-L03                        3       0
      Moto Z2 Play Build/NPSS26.118-19-14                3       0
      Nexus 6 Build/MOB30M                               3       3
      SAMSUNG SM-G950F Build/R16NW                       3       0
      SM-G900M Build/LRX21T                              3       0
      SM-G925I Build/NRD90M                              3       1
      SM-G935V Build/NRD90M                              3       0
      SM-J700M Build/MMB29K                              3       0
      SM-J710MN Build/MMB29K                             3       0
      SM-J730GM Build/NRD90M                             3       0
      SM-N950F Build/NMF26X                              3       0
      F5121 Build/34.4.A.2.19                            2       0
      F5321                                              2       0
      Hisense U963 Build/MRA58K                          2       2
      LG-D320 Build/KOT49I.V10a                          2       2
      LG-M700 Build/NMF26X                               2       0
      M4 SS4458 Build/MMB29M                             2       0
      Moto C Build/NRD90M.063                            2       0
      Moto G (5) Build/NPP25.137-93                      2       0
      Moto G (5) Plus Build/NPN25.137-92                 2       2
      RNE-L03 Build/HUAWEIRNE-L03                        2       0
      SAMSUNG SM-G610M Build/MMB29K                      2       0
      SAMSUNG SM-G930F Build/NRD90M                      2       0
      SAMSUNG SM-J120H Build/LMY47V                      2       0
      SM-G610M Build/MMB29K                              2       0
      SM-J510MN Build/MMB29M                             2       2
      ZEIA8                                              2       2
      rv:57.0                                            2       0
      rv:58.0                                            2       2
      rv:59.0                                            2       0
      0PM92                                              1       1
      5010G Build/MRA58K                                 1       0
      5025G Build/LMY47I                                 1       1
      BLL-L23 Build/HUAWEIBLL-L23                        1       0
      Blade L2 Plus Build/KOT49H                         1       1
      CRO-L03 Build/HUAWEICRO-L03                        1       1
      Dream                                              1       1
      F3113 Build/33.3.A.1.97                            1       0
      HTC Desire 10 lifestyle Build/MMB29M               1       1
      HTC Desire 650 Build/MMB29M                        1       0
      HTC One_M8 Build/MRA58K                            1       0
      HUAWEI RIO-L03 Build/HUAWEIRIO-L03                 1       0
      LG-D680 Build/KOT49I                               1       1
      LG-H542 Build/LRX22G                               1       0
      LG-H650 Build/MRA58K                               1       1
      LG-H990 Build/NRD90M                               1       0
      LG-K220 Build/MXB48T                               1       0
      Lenovo PB2-650Y Build/MRA58K                       1       0
      MHA-L09 Build/HUAWEIMHA-L09                        1       0
      Mi                                                 1       1
      Moto G (4) Build/NPJS25.93-14-15                   1       1
      Moto G (4) Build/NPJS25.93-14-8.1-4                1       1
      Moto G Play Build/MPIS24.241-15.3-7                1       0
      Moto X Play Build/NPD26.48-24-1                    1       1
      MotoG3 Build/MPIS24.65-33.1-2-16                   1       1
      Robin                                              1       0
      SAMSUNG                                            1       0
      SAMSUNG SM-G570M Build/NRD90M                      1       0
      SAMSUNG SM-G935F Build/NRD90M                      1       0
      SAMSUNG SM-G950F Build/NRD90M                      1       0
      SAMSUNG SM-N950F Build/NMF26X                      1       0
      SLA-L03 Build/HUAWEISLA-L03                        1       0
      SM-A520F Build/NRD90M                              1       0
      SM-A720F Build/NRD90M                              1       0
      SM-G531H Build/LMY48B                              1       1
      SM-G532M Build/MMB29T                              1       0
      SM-G570M Build/MMB29K                              1       0
      SM-G720AX                                          1       0
      SM-G920I                                           1       0
      SM-G920P Build/NRD90M                              1       1
      SM-G930F Build/NRD90M                              1       0
      SM-G930T Build/NRD90M                              1       0
      SM-G950F Build/NRD90M                              1       0
      SM-G955F Build/NRD90M                              1       0
      SM-G955U Build/NRD90M                              1       1
      SM-J105B Build/LMY47V                              1       1
      SM-J111M Build/LMY47V                              1       0
      SM-J701M Build/NRD90M                              1       1
      SM-N900W8 Build/LRX21V                             1       1
      SM-N950U Build/NMF26X                              1       0
      SM-P550                                            1       0
      SM-T113NU Build/KTU84P                             1       0
      SM-T530                                            1       1
      SM-T800                                            1       0
      SM-T820 Build/NRD90M                               1       0
      TA-1039 Build/N2G47H                               1       1
      TA-1039 Build/NMF26F                               1       1
      VS5012 Build/NRD90M                                1       1
      XT1580                                             1       0
      XT1635-02 Build/NPN26.118-22-2                     1       0
      iPhone                                             1       1
      rv:38.0                                            1       0
      rv:45.0                                            1       0
      rv:48.0                                            1       0
      rv:60.0                                            1       0
2256  Windows                                          364      60
      Trident/7.0                                       37       0
      SM-A300H Build/LRX22G                             20      20
      ALE-L23 Build/HuaweiALE-L23                       16       0
      SAMSUNG SM-J730GM Build/NRD90M                    14       0
      SM-G935F Build/NRD90M                             12       0
      rv:59.0                                            9       0
      MotoG3 Build/MPIS24.65-33.1-2-16                   8       6
      SM-G531H Build/LMY48B                              8       2
      SM-J700M Build/MMB29K                              8       1
      rv:57.0                                            8       5
      BAC-L03 Build/HUAWEIBAC-L03                        7       0
      HUAWEI CUN-L03 Build/HUAWEICUN-L03                 7       0
      Moto G (4) Build/NPJS25.93-14-10                   7       2
      SAMSUNG SM-J700M Build/MMB29K                      7       7
      HTC Desire 10 lifestyle Build/MMB29M               6       0
      SM-G935V Build/NRD90M                              6       0
      SM-G950F Build/R16NW                               6       1
      HTC Desire 626s Build/LMY47O                       5       1
      rv:58.0                                            5       2
      BLADE V8 SE Build/NRD90M                           4       4
      LG-D693n Build/LRX22G                              4       0
      Moto G (5) Plus Build/NPN25.137-92                 4       0
      Moto Z2 Play Build/NPSS26.118-19-14                4       0
      MotoG3-TE Build/MPDS24.65-33-1-3                   4       4
      SM-A500M Build/KTU84P                              4       0
      SM-A500M Build/LRX22G                              4       3
      TA-1039 Build/NMF26F                               4       1
      5025G Build/LMY47I                                 3       3
      7048A Build/LRX22G                                 3       0
      Blade V6 Plus Build/MRA58K                         3       0
      CAM-L03 Build/HUAWEICAM-L03                        3       1
      HTC Desire 530 Build/MMB29M                        3       0
      HUAWEI RIO-L03 Build/HUAWEIRIO-L03                 3       0
      LG-K500 Build/MMB29M                               3       0
      LG-K580 Build/MRA58K                               3       1
      LG-M700 Build/NMF26X                               3       0
      Moto E (4) Build/NMA26.42-19                       3       0
      Moto E (4) Plus Build/NMA26.42-69                  3       1
      Moto G (5) Plus Build/NPN25.137-82                 3       1
      SM-G950F Build/NRD90M                              3       0
      SM-G955F Build/NRD90M                              3       0
      SM-G955U Build/NRD90M                              3       3
      rv:56.0                                            3       0
      ALP-L09 Build/HUAWEIALP-L09S                       2       0
      BLADE A520 Build/NRD90M                            2       0
      BLADE A602 Build/MRA58K                            2       0
      Blade V580 Build/LMY47D                            2       0
      HUAWEI TAG-L13 Build/HUAWEITAG-L13                 2       0
      HUAWEI VNS-L53 Build/HUAWEIVNS-L53                 2       0
      Hisense F23 Build/NRD90M                           2       2
      LG-D331                                            2       2
      LG-H840 Build/MMB29M                               2       0
      LG-K530 Build/MMB29M                               2       0
      LG-X230 Build/MRA58K                               2       0
      Lenovo A2016b30 Build/MRA58K                       2       1
      MYA-L13 Build/HUAWEIMYA-L13                        2       1
      Moto G (5) Build/NPP25.137-82                      2       0
      Moto G (5) Build/NPP25.137-93                      2       0
      PRA-LX3 Build/HUAWEIPRA-LX3                        2       0
      RNE-L03 Build/HUAWEIRNE-L03                        2       2
      SAMSUNG SM-A720F Build/NRD90M                      2       0
      SAMSUNG SM-T710 Build/NRD90M                       2       1
      SM-A520F Build/NRD90M                              2       0
      SM-A720F Build/NRD90M                              2       0
      SM-G532M Build/MMB29T                              2       2
      SM-G610M Build/MMB29K                              2       0
      SM-G615F                                           2       2
      SM-G900T Build/MMB29M                              2       0
      SM-G935F Build/MMB29K                              2       0
      SM-J730GM Build/NRD90M                             2       2
      SM-N900W8 Build/LRX21V                             2       0
      SM-P550 Build/MMB29M                               2       0
      SM-T700 Build/MMB29K                               2       0
      WAS-LX3 Build/HUAWEIWAS-LX3                        2       0
      XT1635-02 Build/NPN26.118-22-2                     2       2
      moto x4 Build/NPW26.83-18-2-0-4                    2       1
      rv:11.0                                            2       0
      rv:48.0                                            2       0
      5012G Build/MRA58K                                 1       0
      ALCATEL ONE TOUCH 7047A Build/JDQ39                1       0
      Blade A475 Build/LMY47D                            1       1
      CHC-U03 Build/HuaweiCHC-U03                        1       1
      CRO-L03 Build/HUAWEICRO-L03                        1       0
      D5316 Build/19.4.A.0.182                           1       0
      D6603 Build/23.5.A.1.291                           1       0
      E5306 Build/27.3.A.0.129                           1       1
      E5606                                              1       0
      E5803 Build/32.4.A.1.54                            1       0
      F3113 Build/33.3.A.1.97                            1       0
      F3213 Build/36.1.A.1.86                            1       0
      GT-I9060L Build/JDQ39                              1       0
      GT-I9060M Build/KTU84P                             1       1
      GT-P5110                                           1       0
      HUAWEI VNS-L23 Build/HUAWEIVNS-L23                 1       0
      Hisense L675 Build/MRA58K                          1       0
      Ilium L1120 Build/NRD90M                           1       0
      Ilium L610 Build/MRA58K                            1       0
      LG-D320 Build/KOT49I.V10a                          1       1
      LG-D331 Build/LRX22G                               1       0
      LG-D680 Build/KOT49I                               1       0
      LG-D855                                            1       1
      LG-H320 Build/LRX21Y                               1       0
      LG-H500 Build/LRX21Y                               1       0
      LG-H870 Build/NRD90U                               1       0
      LG-K200 Build/MXB48T                               1       0
      LG-K220 Build/MXB48T                               1       0
      LG-K410 Build/LRX22G                               1       0
      LG-K530 Build/NRD90U                               1       0
      LG-M153 Build/MXB48T                               1       0
      LG-P714                                            1       0
      LG-X180g Build/LMY47I                              1       0
      LG-X220 Build/LMY47I                               1       0
      LG-X240 Build/MRA58K                               1       0
      Lenovo                                             1       0
      Lenovo K33b36 Build/MMB29M                         1       0
      Lenovo PB2-650Y Build/MRA58K                       1       0
      MOT-A6020l37 Build/LMY47V                          1       0
      Moto C Build/NRD90M.063                            1       0
      Moto C Plus Build/NRD90M.05.022                    1       1
      Moto G (4) Build/NPJ25.93-14.5                     1       1
      Moto G (4) Build/NPJ25.93-14.7                     1       0
      Moto G (4) Build/NPJS25.93-14-13                   1       0
      Moto G (4) Build/NPJS25.93-14-15                   1       1
      Moto G (4) Build/NPJS25.93-14-8                    1       0
      Moto G (4) Build/NPJS25.93-14-8.1-4                1       1
      Moto G (5) Build/NPP25.137-38                      1       1
      Moto G (5) Build/NPPS25.137-15-11                  1       0
      Moto G (5) Build/NPPS25.137-93-4                   1       0
      Moto G Play Build/MPIS24.241-15.3-7                1       0
      Moto X Play Build/NPD26.48-24-1                    1       0
      MotoG3-TE Build/MPDS24.65-33-1-30                  1       0
      R831L                                              1       0
      Redmi 5 Plus Build/N2G47H                          1       0
      SAMSUNG                                            1       0
      SAMSUNG SM-G950F Build/R16NW                       1       0
      SAMSUNG SM-J327P Build/MMB29M                      1       0
      SAMSUNG SM-J701M Build/NRD90M                      1       0
      SAMSUNG-SM-G900A Build/LMY47X                      1       0
      SAMSUNG-SM-G930A Build/NRD90M                      1       0
      SLA-L03 Build/HUAWEISLA-L03                        1       0
      SM-A320Y Build/NRD90M                              1       0
      SM-A730F Build/NMF26X                              1       0
      SM-G355M Build/KOT49H                              1       0
      SM-G570M Build/MMB29K                              1       0
      SM-G570M Build/NRD90M                              1       0
      SM-G900H Build/MMB29K                              1       0
      SM-G925I Build/NRD90M                              1       0
      SM-G9650 Build/R16NW                               1       0
      SM-J200M Build/LMY47X                              1       0
      SM-J320M Build/LMY47V                              1       0
      SM-J500M Build/LMY48B                              1       0
      SM-J500M Build/MMB29M                              1       0
      SM-J710MN Build/MMB29K                             1       0
      SM-N950F Build/NMF26X                              1       0
      SM-N950U Build/NMF26X                              1       0
      SM-P355M Build/MMB29M                              1       0
      SM-T113NU Build/KTU84P                             1       1
      SM-T230 Build/KOT49H                               1       0
      SM-T310 Build/KOT49H                               1       0
      SM-T560 Build/KTU84P                               1       0
      TRT-L53 Build/HUAWEITRT-L53                        1       0
      Windows NT 6.2                                     1       1
      XT1563                                             1       0
      XT1650 Build/NPLS26.118-20-5-11                    1       0
      ZTE BLADE V8 MINI Build/NRD90M                     1       0
      es-mx                                              1       0
      es-us                                              1       0
      rv:52.0                                            1       0
4504  Windows                                          289      54
      Trident/7.0                                       32       0
      rv:11.0                                            9       0
      SM-A300H Build/LRX22G                              7       7
      rv:58.0                                            7       3
      rv:59.0                                            7       0
      SM-G610M Build/MMB29K                              6       0
      MYA-L03 Build/HUAWEIMYA-L03                        5       5
      TRT-L53 Build/HUAWEITRT-L53                        5       5
      CAM-L03 Build/HUAWEICAM-L03                        4       1
      Moto E (4) Plus Build/NMA26.42-69                  4       4
      VS5012 Build/NRD90M                                4       4
      rv:55.0                                            4       0
      Ilium L620 Build/NRD90M                            3       0
      LG-D320 Build/KOT49I.V10a                          3       3
      M4 SS4456 Build/LMY47V                             3       0
      SAMSUNG                                            3       0
      SAMSUNG SM-T810 Build/NRD90M                       3       0
      SM-A500M Build/KTU84P                              3       0

In [28]:
# Cards connected to the suspicious target device
target_device = "SM-A300H Build/LRX22G"

target_cards = (
    df.loc[
        df["DeviceInfo"] == target_device,
        "card1"
    ]
    .dropna()
    .unique()
)

# Device signatures used by those cards
cluster_devices = (
    df[
        df["card1"].isin(target_cards) &
        df["DeviceInfo"].notna()
    ]
    .groupby("DeviceInfo")
    .agg(
        transactions=("TransactionID", "count"),
        unique_cards=("card1", "nunique"),
        frauds=("isFraud", "sum"),
        fraud_rate=("isFraud", "mean")
    )
)

# Remove very generic/high-volume device signatures
# for the purpose of network analysis.
specific_devices = cluster_devices[
    (cluster_devices["transactions"] <= 1000) &
    (cluster_devices["unique_cards"] >= 2)
].sort_values(
    ["unique_cards", "fraud_rate"],
    ascending=[False, False]
)

print(
    specific_devices.head(50).to_string()
)

                                      transactions  unique_cards  frauds  fraud_rate
DeviceInfo
SM-A300H Build/LRX22G                          203            52     169    0.832512
rv:57.0                                        184            35      60    0.326087
SM-G531H Build/LMY48B                          368            33      23    0.062500
SM-G610M Build/MMB29K                          357            32      32    0.089636
rv:11.0                                        238            31       8    0.033613
SM-J700M Build/MMB29K                          435            30      50    0.114943
ALE-L23 Build/HuaweiALE-L23                    270            29      23    0.085185
SM-G935F Build/NRD90M                          244            28      23    0.094262
SM-G532M Build/MMB29T                          270            28      11    0.040741
rv:58.0                                         87            27      22    0.252874
SM-G950F Build/NRD90M                          137            26      16    0.116788
SM-J730GM Build/NRD90M                         159            25      19    0.119497
MotoG3 Build/MPIS24.65-33.1-2-16                77            24      23    0.298701
Moto G (4) Build/NPJ25.93-14.7                 197            24      34    0.172589
rv:59.0                                        121            24      16    0.132231
Moto G (4) Build/NPJS25.93-14-13               122            24      12    0.098361
Moto X Play Build/NPD26.48-24-1                101            24       1    0.009901
Moto G Play Build/MPIS24.241-15.3-7            122            23      17    0.139344
SM-A720F Build/NRD90M                           96            23      12    0.125000
CAM-L03 Build/HUAWEICAM-L03                    148            22      19    0.128378
Moto G (5) Plus Build/NPN25.137-92              86            22       9    0.104651
HUAWEI TAG-L13 Build/HUAWEITAG-L13             101            22      10    0.099010
LG-D320 Build/KOT49I.V10a                       55            21      47    0.854545
Moto Z2 Play Build/NPSS26.118-19-14             94            21      22    0.234043
BLADE V8 SE Build/NRD90M                        87            21      20    0.229885
LG-K410 Build/LRX22G                           126            21       4    0.031746
SM-G570M Build/MMB29K                          156            21       3    0.019231
SM-A520F Build/NRD90M                          113            21       0    0.000000
SM-J701M Build/NRD90M                          135            20      29    0.214815
XT1635-02 Build/NPN26.118-22-2                  78            20      15    0.192308
Moto G (4) Build/NPJS25.93-14-10                84            20      16    0.190476
Moto E (4) Plus Build/NMA26.42-69              137            20      24    0.175182
HUAWEI VNS-L23 Build/HUAWEIVNS-L23              83            20      14    0.168675
Moto G (5) Build/NPPS25.137-15-11               58            20       8    0.137931
SM-J510MN Build/MMB29M                         138            20      16    0.115942
LG-M700 Build/NMF26X                           132            20      10    0.075758
SAMSUNG                                         53            20       2    0.037736
LG-H500 Build/LRX21Y                            60            20       1    0.016667
PRA-LX3 Build/HUAWEIPRA-LX3                    113            20       0    0.000000
HTC Desire 10 lifestyle Build/MMB29M            85            19      21    0.247059
TRT-L53 Build/HUAWEITRT-L53                     97            19      13    0.134021
SM-G530H Build/LRX22G                           58            19       5    0.086207
Moto C Build/NRD90M.063                         71            19       5    0.070423
LG-X230 Build/MRA58K                            88            19       6    0.068182
F3113 Build/33.3.A.1.97                         63            19       3    0.047619
LG-X180g Build/LMY47I                           74            19       3    0.040541
HUAWEI VNS-L53 Build/HUAWEIVNS-L53             104            19       3    0.028846
LG-K200 Build/MXB48T                            75            19       1    0.013333
SM-J700M Build/LMY48B                           87            18      12    0.137931
SM-G900M Build/LRX21T                           72            18       9    0.125000

In [29]:
# Keep only the strongest shared device signatures
top_devices = specific_devices.head(15).index

links = (
    df[
        df["card1"].isin(target_cards) &
        df["DeviceInfo"].isin(top_devices)
    ][["card1", "DeviceInfo", "isFraud"]]
    .drop_duplicates()
    .sort_values(["DeviceInfo", "card1"])
)

print(links.to_string(index=False))

 card1                       DeviceInfo  isFraud
  1976      ALE-L23 Build/HuaweiALE-L23        1
  1976      ALE-L23 Build/HuaweiALE-L23        0
  2256      ALE-L23 Build/HuaweiALE-L23        0
  2650      ALE-L23 Build/HuaweiALE-L23        0
  3154      ALE-L23 Build/HuaweiALE-L23        0
  3154      ALE-L23 Build/HuaweiALE-L23        1
  4461      ALE-L23 Build/HuaweiALE-L23        0
  4461      ALE-L23 Build/HuaweiALE-L23        1
  5365      ALE-L23 Build/HuaweiALE-L23        0
  5365      ALE-L23 Build/HuaweiALE-L23        1
  5595      ALE-L23 Build/HuaweiALE-L23        0
  5812      ALE-L23 Build/HuaweiALE-L23        0
  5943      ALE-L23 Build/HuaweiALE-L23        0
  7949      ALE-L23 Build/HuaweiALE-L23        0
  8755      ALE-L23 Build/HuaweiALE-L23        1
  8755      ALE-L23 Build/HuaweiALE-L23        0
  9026      ALE-L23 Build/HuaweiALE-L23        0
  9065      ALE-L23 Build/HuaweiALE-L23        0
  9633      ALE-L23 Build/HuaweiALE-L23        0
  9633      ALE-L23 Build/HuaweiALE-L23        1
  9917      ALE-L23 Build/HuaweiALE-L23        0
  9917      ALE-L23 Build/HuaweiALE-L23        1
 10086      ALE-L23 Build/HuaweiALE-L23        0
 10568      ALE-L23 Build/HuaweiALE-L23        0
 10876      ALE-L23 Build/HuaweiALE-L23        1
 10876      ALE-L23 Build/HuaweiALE-L23        0
 11201      ALE-L23 Build/HuaweiALE-L23        0
 12778      ALE-L23 Build/HuaweiALE-L23        1
 13413      ALE-L23 Build/HuaweiALE-L23        0
 13832      ALE-L23 Build/HuaweiALE-L23        0
 13832      ALE-L23 Build/HuaweiALE-L23        1
 14276      ALE-L23 Build/HuaweiALE-L23        1
 14276      ALE-L23 Build/HuaweiALE-L23        0
 14543      ALE-L23 Build/HuaweiALE-L23        1
 15885      ALE-L23 Build/HuaweiALE-L23        0
 15885      ALE-L23 Build/HuaweiALE-L23        1
 16062      ALE-L23 Build/HuaweiALE-L23        0
 16136      ALE-L23 Build/HuaweiALE-L23        0
 17147      ALE-L23 Build/HuaweiALE-L23        0
 18301      ALE-L23 Build/HuaweiALE-L23        0
  2256   Moto G (4) Build/NPJ25.93-14.7        0
  2650   Moto G (4) Build/NPJ25.93-14.7        0
  3154   Moto G (4) Build/NPJ25.93-14.7        0
  4461   Moto G (4) Build/NPJ25.93-14.7        0
  4504   Moto G (4) Build/NPJ25.93-14.7        1
  5365   Moto G (4) Build/NPJ25.93-14.7        0
  5812   Moto G (4) Build/NPJ25.93-14.7        0
  9026   Moto G (4) Build/NPJ25.93-14.7        0
  9633   Moto G (4) Build/NPJ25.93-14.7        0
  9633   Moto G (4) Build/NPJ25.93-14.7        1
  9917   Moto G (4) Build/NPJ25.93-14.7        1
  9917   Moto G (4) Build/NPJ25.93-14.7        0
 10086   Moto G (4) Build/NPJ25.93-14.7        0
 10568   Moto G (4) Build/NPJ25.93-14.7        0
 10876   Moto G (4) Build/NPJ25.93-14.7        1
 11201   Moto G (4) Build/NPJ25.93-14.7        0
 13832   Moto G (4) Build/NPJ25.93-14.7        0
 14276   Moto G (4) Build/NPJ25.93-14.7        1
 14543   Moto G (4) Build/NPJ25.93-14.7        0
 15885   Moto G (4) Build/NPJ25.93-14.7        0
 15890   Moto G (4) Build/NPJ25.93-14.7        0
 16062   Moto G (4) Build/NPJ25.93-14.7        0
 16136   Moto G (4) Build/NPJ25.93-14.7        0
 16346   Moto G (4) Build/NPJ25.93-14.7        1
 17188   Moto G (4) Build/NPJ25.93-14.7        0
 18301   Moto G (4) Build/NPJ25.93-14.7        0
  1976 MotoG3 Build/MPIS24.65-33.1-2-16        1
  2256 MotoG3 Build/MPIS24.65-33.1-2-16        0
  2256 MotoG3 Build/MPIS24.65-33.1-2-16        1
  2650 MotoG3 Build/MPIS24.65-33.1-2-16        0
  3154 MotoG3 Build/MPIS24.65-33.1-2-16        0
  3867 MotoG3 Build/MPIS24.65-33.1-2-16        0
  4461 MotoG3 Build/MPIS24.65-33.1-2-16        0
  4461 MotoG3 Build/MPIS24.65-33.1-2-16        1
  4504 MotoG3 Build/MPIS24.65-33.1-2-16        0
  5812 MotoG3 Build/MPIS24.65-33.1-2-16        1
  5943 MotoG3 Build/MPIS24.65-33.1-2-16        1
  7949 MotoG3 Build/MPIS24.65-33.1-2-16        0
  9026 MotoG3 Build/MPIS24.65-33.1-2-16        1
  9633 MotoG3 Build/MPIS24.65-33.1-2-16        0
  9633 MotoG3 Build/MPIS24.65-33.1-2-16        1
  9917 MotoG3 Build/MPIS24.65-33.1-2-16        0
 10086 MotoG3 Build/MPIS24.65-33.1-2-16        1
 10369 MotoG3 Build/MPIS24.65-33.1-2-16        0
 10568 MotoG3 Build/MPIS24.65-33.1-2-16        0
 10876 MotoG3 Build/MPIS24.65-33.1-2-16        1
 11201 MotoG3 Build/MPIS24.65-33.1-2-16        0
 13832 MotoG3 Build/MPIS24.65-33.1-2-16        0
 14276 MotoG3 Build/MPIS24.65-33.1-2-16        0
 15885 MotoG3 Build/MPIS24.65-33.1-2-16        0
 16062 MotoG3 Build/MPIS24.65-33.1-2-16        1
 16062 MotoG3 Build/MPIS24.65-33.1-2-16        0
 16095 MotoG3 Build/MPIS24.65-33.1-2-16        1
 16136 MotoG3 Build/MPIS24.65-33.1-2-16        0
  1976            SM-A300H Build/LRX22G        1
  2256            SM-A300H Build/LRX22G        1
  2650            SM-A300H Build/LRX22G        0
  2801            SM-A300H Build/LRX22G        1
  3154            SM-A300H Build/LRX22G        0
  3154            SM-A300H Build/LRX22G        1
  3867            SM-A300H Build/LRX22G        1
  3887            SM-A300H Build/LRX22G        1
  3901            SM-A300H Build/LRX22G        1
  4461            SM-A300H Build/LRX22G        0
  4461            SM-A300H Build/LRX22G        1
  4504            SM-A300H Build/LRX22G        1
  5009            SM-A300H Build/LRX22G        0
  5365            SM-A300H Build/LRX22G        1
  5535            SM-A300H Build/LRX22G        0
  5595            SM-A300H Build/LRX22G        0
  5629            SM-A300H Build/LRX22G        1
  5812            SM-A300H Build/LRX22G        1
  5812            SM-A300H Build/LRX22G        0
  5943            SM-A300H Build/LRX22G        1
  7099            SM-A300H Build/LRX22G        1
  7205            SM-A300H Build/LRX22G        1
  7585            SM-A300H Build/LRX22G        1
  7949            SM-A300H Build/LRX22G        1
  8755            SM-A300H Build/LRX22G        1
  9026            SM-A300H Build/LRX22G        1
  9065            SM-A300H Build/LRX22G        0
  9633            SM-A300H Build/LRX22G        0
  9633            SM-A300H Build/LRX22G        1
  9917            SM-A300H Build/LRX22G        1
  9917            SM-A300H Build/LRX22G        0
 10054            SM-A300H Build/LRX22G        1
 10086            SM-A300H Build/LRX22G        1
 10369            SM-A300H Build/LRX22G        1
 10553            SM-A300H Build/LRX22G        1
 10568            SM-A300H Build/LRX22G        0
 10876            SM-A300H Build/LRX22G        1
 11201            SM-A300H Build/LRX22G        1
 12778            SM-A300H Build/LRX22G        1
 12839            SM-A300H Build/LRX22G        1
 13335            SM-A300H Build/LRX22G        1
 13346            SM-A300H Build/LRX22G        0
 13413            SM-A300H Build/LRX22G        1
 13832            SM-A300H Build/LRX22G        0
 13832            SM-A300H Build/LRX22G        1
 14276            SM-A300H Build/LRX22G        1
 14543            SM-A300H Build/LRX22G        1
 15885            SM-A300H Build/LRX22G        0
 15885            SM-A300H Build/LRX22G        1
 15890            SM-A300H Build/LRX22G        1
 16062            SM-A300H Build/LRX22G        1
 16095            SM-A300H Build/LRX22G        1
 16136            SM-A300H Build/LRX22G        0
 16346            SM-A300H Build/LRX22G        1
 16578            SM-A300H Build/LRX22G        1
 17147            SM-A300H Build/LRX22G        1
 17188            SM-A300H Build/LRX22G        1
 18282            SM-A300H Build/LRX22G        1
 18301            SM-A300H Build/LRX22G        1
  1976            SM-G531H Build/LMY48B        1
  2256            SM-G531H Build/LMY48B        0
  2256            SM-G531H Build/LMY48B        1
  2650            SM-G531H Build/LMY48B        0
  2801            SM-G531H Build/LMY48B        1
  2801            SM-G531H Build/LMY48B        0
  3154            SM-G531H Build/LMY48B        0
  3867            SM-G531H Build/LMY48B        0
  3887            SM-G531H Build/LMY48B        0
  4461            SM-G531H Build/LMY48B        0
  5365            SM-G531H Build/LMY48B        0
  5595            SM-G531H Build/LMY48B        0
  5812            SM-G531H Build/LMY48B        0
  5812            SM-G531H Build/LMY48B        1
  7949            SM-G531H Build/LMY48B        0
  8755            SM-G531H Build/LMY48B        0
  9026            SM-G531H Build/LMY48B        0
  9026            SM-G531H Build/LMY48B        1
  9633            SM-G531H Build/LMY48B        0
  9633            SM-G531H Build/LMY48B        1
  9917            SM-G531H Build/LMY48B        0
 10086            SM-G531H Build/LMY48B        0
 10369            SM-G531H Build/LMY48B        1
 10369            SM-G531H Build/LMY48B        0
 10568            SM-G531H Build/LMY48B        0
 10876            SM-G531H Build/LMY48B        0
 11201            SM-G531H Build/LMY48B        0
 13346            SM-G531H Build/LMY48B        0
 13413            SM-G531H Build/LMY48B        0
 13832            SM-G531H Build/LMY48B        0
 14276            SM-G531H Build/LMY48B        0
 14543            SM-G531H Build/LMY48B        0
 15885            SM-G531H Build/LMY48B        0
 15885            SM-G531H Build/LMY48B        1
 15890            SM-G531H Build/LMY48B        1
 16062            SM-G531H Build/LMY48B        0
 16095            SM-G531H Build/LMY48B        0
 16136            SM-G531H Build/LMY48B        0
 16346            SM-G531H Build/LMY48B        0
 18301            SM-G531H Build/LMY48B        0
  1976            SM-G532M Build/MMB29T        0
  2256            SM-G532M Build/MMB29T        1
  2650            SM-G532M Build/MMB29T        0
  3154            SM-G532M Build/MMB29T        0
  3867            SM-G532M Build/MMB29T        0
  3867            SM-G532M Build/MMB29T        1
  3887            SM-G532M Build/MMB29T        0
  4461            SM-G532M Build/MMB29T        0
  4504            SM-G532M Build/MMB29T        1
  5812            SM-G532M Build/MMB29T        0
  7949            SM-G532M Build/MMB29T        0
  8755            SM-G532M Build/MMB29T        0
  9026            SM-G532M Build/MMB29T        1
  9026            SM-G532M Build/MMB29T        0
  9633            SM-G532M Build/MMB29T        0
  9917            SM-G532M Build/MMB29T        0
 10086            SM-G532M Build/MMB29T        0
 10369            SM-G532M Build/MMB29T        0
 10568            SM-G532M Build/MMB29T        0
 10876            SM-G532M Build/MMB29T        0
 10876            SM-G532M Build/MMB29T        1
 11201            SM-G532M Build/MMB29T        0
 13413            SM-G532M Build/MMB29T        0
 13832            SM-G532M Build/MMB29T        0
 14276            SM-G532M Build/MMB29T        1
 14276            SM-G532M Build/MMB29T        0
 14543            SM-G532M Build/MMB29T        0
 15885            SM-G532M Build/MMB29T        0
 16062            SM-G532M Build/MMB29T        1
 16062            SM-G532M Build/MMB29T        0
 16136            SM-G532M Build/MMB29T        0
 16346            SM-G532M Build/MMB29T        0
 18301            SM-G532M Build/MMB29T        0
  1976            SM-G610M Build/MMB29K        0
  2256            SM-G610M Build/MMB29K        0
  2650            SM-G610M Build/MMB29K        0
  2801            SM-G610M Build/MMB29K        1
  2801            SM-G610M Build/MMB29K        0
  3154            SM-G610M Build/MMB29K        0
  3154            SM-G610M Build/MMB29K        1
  3867            SM-G610M Build/MMB29K        0
  3887            SM-G610M Build/MMB29K        0
  4461            SM-G610M Build/MMB29K        0
  4461            SM-G610M Build/MMB29K        1
  4504            SM-G610M Build/MMB29K        0
  5365            SM-G610M Build/MMB29K        0
  5365            SM-G610M Build/MMB29K        1
  5595            SM-G610M Build/MMB29K        0
  5812            SM-G610M Build/MMB29K        0
  5812            SM-G610M Build/MMB29K        1
  7949            SM-G610M Build/MMB29K        0
  8755            SM-G610M Build/MMB29K        0
  8755            SM-G610M Build/MMB29K        1
  9026            SM-G610M Build/MMB29K        0
  9633            SM-G610M Build/MMB29K        0
  9633            SM-G610M Build/MMB29K        1
  9917            SM-G610M Build/MMB29K        0
 10086            SM-G610M Build/MMB29K        1
 10086            SM-G610M Build/MMB29K        0
 10568            SM-G610M Build/MMB29K        0
 10568            SM-G610M Build/MMB29K        1
 10876            SM-G610M Build/MMB29K        0
 10876            SM-G610M Build/MMB29K        1
 11201            SM-G610M Build/MMB29K        0
 11201            SM-G610M Build/MMB29K        1
 12778            SM-G610M Build/MMB29K        0
 13413            SM-G610M Build/MMB29K        0
 13832            SM-G610M Build/MMB29K        0
 14276            SM-G610M Build/MMB29K        0
 15885            SM-G610M Build/MMB29K        0
 15885            SM-G610M Build/MMB29K        1
 16062            SM-G610M Build/MMB29K        0
 16095            SM-G610M Build/MMB29K        0
 16136            SM-G610M Build/MMB29K        0
 16346            SM-G610M Build/MMB29K        0
 17147            SM-G610M Build/MMB29K        1
 18301            SM-G610M Build/MMB29K        0
  1976            SM-G935F Build/NRD90M        0
  2256            SM-G935F Build/NRD90M        0
  2650            SM-G935F Build/NRD90M        0
  2801            SM-G935F Build/NRD90M        0
  2801            SM-G935F Build/NRD90M        1
  3154            SM-G935F Build/NRD90M        0
  3154            SM-G935F Build/NRD90M        1
  3887            SM-G935F Build/NRD90M        0
  4461            SM-G935F Build/NRD90M        0
  4504            SM-G935F Build/NRD90M        0
  5365            SM-G935F Build/NRD90M        0
  5812            SM-G935F Build/NRD90M        1
  5812            SM-G935F Build/NRD90M        0
  7099            SM-G935F Build/NRD90M        0
  7949            SM-G935F Build/NRD90M        0
  8755            SM-G935F Build/NRD90M        0
  9026            SM-G935F Build/NRD90M        1
  9026            SM-G935F Build/NRD90M        0
  9633            SM-G935F Build/NRD90M        0
  9633            SM-G935F Build/NRD90M        1
 10086            SM-G935F Build/NRD90M        0
 10369            SM-G935F Build/NRD90M        0
 10876            SM-G935F Build/NRD90M        1
 10876            SM-G935F Build/NRD90M        0
 11201            SM-G935F Build/NRD90M        0
 11201            SM-G935F Build/NRD90M        1
 12778            SM-G935F Build/NRD90M        0
 13413            SM-G935F Build/NRD90M        0
 13832            SM-G935F Build/NRD90M        0
 14276            SM-G935F Build/NRD90M        0
 14276            SM-G935F Build/NRD90M        1
 14543            SM-G935F Build/NRD90M        0
 15885            SM-G935F Build/NRD90M        0
 15890            SM-G935F Build/NRD90M        0
 16062            SM-G935F Build/NRD90M        0
 16136            SM-G935F Build/NRD90M        0
  1976            SM-G950F Build/NRD90M        0
  2256            SM-G950F Build/NRD90M        0
  2650            SM-G950F Build/NRD90M        0
  2801            SM-G950F Build/NRD90M        0
  2801            SM-G950F Build/NRD90M        1
  3154            SM-G950F Build/NRD90M        0
  3887            SM-G950F Build/NRD90M        0
  3901            SM-G950F Build/NRD90M        0
  4461            SM-G950F Build/NRD90M        0
  5009            SM-G950F Build/NRD90M        0
  5812            SM-G950F Build/NRD90M        0
  7099            SM-G950F Build/NRD90M        1
  9026            SM-G950F Build/NRD90M        1
  9026            SM-G950F Build/NRD90M        0
  9065            SM-G950F Build/NRD90M        0
  9633            SM-G950F Build/NRD90M        0
  9633            SM-G950F Build/NRD90M        1
  9917            SM-G950F Build/NRD90M        0
 10086            SM-G950F Build/NRD90M        0
 10369            SM-G950F Build/NRD90M        0
 10568            SM-G950F Build/NRD90M        0
 10568            SM-G950F Build/NRD90M        1
 10876            SM-G950F Build/NRD90M        0
 11201            SM-G950F Build/NRD90M        0
 13832            SM-G950F Build/NRD90M        0
 13832            SM-G950F Build/NRD90M        1
 15885            SM-G950F Build/NRD90M        0
 16062            SM-G950F Build/NRD90M        0
 16062            SM-G950F Build/NRD90M        1
 16136            SM-G950F Build/NRD90M        0
 16346            SM-G950F Build/NRD90M        1
 16346            SM-G950F Build/NRD90M        0
 17147            SM-G950F Build/NRD90M        0
  1976            SM-J700M Build/MMB29K        0
  2256            SM-J700M Build/MMB29K        0
  2256            SM-J700M Build/MMB29K        1
  2650            SM-J700M Build/MMB29K        0
  3154            SM-J700M Build/MMB29K        0
  3154            SM-J700M Build/MMB29K        1
  4461            SM-J700M Build/MMB29K        0
  4461            SM-J700M Build/MMB29K        1
  5009            SM-J700M Build/MMB29K        0
  5365            SM-J700M Build/MMB29K        0
  5365            SM-J700M Build/MMB29K        1
  5535            SM-J700M Build/MMB29K        0
  5595            SM-J700M Build/MMB29K        0
  5812            SM-J700M Build/MMB29K        0
  5812            SM-J700M Build/MMB29K        1
  5943            SM-J700M Build/MMB29K        1
  7949            SM-J700M Build/MMB29K        0
  8755            SM-J700M Build/MMB29K        0
  8755            SM-J700M Build/MMB29K        1
  9026            SM-J700M Build/MMB29K        0
  9633            SM-J700M Build/MMB29K        0
  9633            SM-J700M Build/MMB29K        1
  9917            SM-J700M Build/MMB29K        0
  9917            SM-J700M Build/MMB29K        1
 10568            SM-J700M Build/MMB29K        1
 10568            SM-J700M Build/MMB29K        0
 10876            SM-J700M Build/MMB29K        0
 10876            SM-J700M Build/MMB29K        1
 11201            SM-J700M Build/MMB29K        0
 11201            SM-J700M Build/MMB29K        1
 12778            SM-J700M Build/MMB29K        0
 12839            SM-J700M Build/MMB29K        0
 13346            SM-J700M Build/MMB29K        0
 13832            SM-J700M Build/MMB29K        0
 13832            SM-J700M Build/MMB29K        1
 14276            SM-J700M Build/MMB29K        0
 14543            SM-J700M Build/MMB29K        1
 14543            SM-J700M Build/MMB29K        0
 15885            SM-J700M Build/MMB29K        0
 15885            SM-J700M Build/MMB29K        1
 16062            SM-J700M Build/MMB29K        0
 16136            SM-J700M Build/MMB29K        0
 16136            SM-J700M Build/MMB29K        1
 16346            SM-J700M Build/MMB29K        0
 18301            SM-J700M Build/MMB29K        1
  1976           SM-J730GM Build/NRD90M        0
  2256           SM-J730GM Build/NRD90M        1
  2650           SM-J730GM Build/NRD90M        0
  2801           SM-J730GM Build/NRD90M        1
  3154           SM-J730GM Build/NRD90M        0
  3867           SM-J730GM Build/NRD90M        0
  4461           SM-J730GM Build/NRD90M        0
  5009           SM-J730GM Build/NRD90M        1
  5595           SM-J730GM Build/NRD90M        0
  5812           SM-J730GM Build/NRD90M        0
  5943           SM-J730GM Build/NRD90M        0
  9026           SM-J730GM Build/NRD90M        1
  9026           SM-J730GM Build/NRD90M        0
  9633           SM-J730GM Build/NRD90M        0
  9633           SM-J730GM Build/NRD90M        1
  9917           SM-J730GM Build/NRD90M        0
 10086           SM-J730GM Build/NRD90M        1
 10568           SM-J730GM Build/NRD90M        0
 11201           SM-J730GM Build/NRD90M        0
 13413           SM-J730GM Build/NRD90M        0
 13832           SM-J730GM Build/NRD90M        0
 14276           SM-J730GM Build/NRD90M        1
 15885           SM-J730GM Build/NRD90M        0

In [30]:
import networkx as nx

# Use only specific/repeated DeviceInfo signatures.
# Exclude extremely generic values for now.
device_counts = (
    df["DeviceInfo"]
    .value_counts(dropna=True)
)

# Initial heuristic:
# DeviceInfo must appear in <= 1000 transactions
# and at least 2 different cards.
candidate_devices = set(
    device_network[
        (device_network["transactions"] <= 1000) &
        (device_network["unique_cards"] >= 2)
    ].index
)

graph_df = df[
    df["card1"].notna() &
    df["DeviceInfo"].isin(candidate_devices)
].copy()

print("Transactions used:", len(graph_df))
print("Cards:", graph_df["card1"].nunique())
print("Device signatures:", graph_df["DeviceInfo"].nunique())

Transactions used: 28468
Cards: 2672
Device signatures: 1232

In [31]:
edge_stats = (
    graph_df
    .groupby(["card1", "DeviceInfo"])
    .agg(
        transactions=("TransactionID", "count"),
        frauds=("isFraud", "sum"),
        fraud_rate=("isFraud", "mean")
    )
    .reset_index()
)

print(edge_stats.head(20).to_string(index=False))

 card1                         DeviceInfo  transactions  frauds  fraud_rate
  1000           F3213 Build/36.0.A.2.146             1       0         0.0
  1011              SM-G950U Build/NRD90M             1       0         0.0
  1012                            rv:48.0             1       0         0.0
  1014            Ilium X220 Build/MRA58K             1       0         0.0
  1015       Moto E (4) Build/NMA26.42-69             1       0         0.0
  1015                               PH-1             2       0         0.0
  1015                              Pixel             1       0         0.0
  1015                            SAMSUNG             1       0         0.0
  1018              SM-J200M Build/LMY47X             1       0         0.0
  1023              SM-G950U Build/NRD90M             1       0         0.0
  1027              SM-G920F Build/NRD90M             1       0         0.0
  1027              SM-G920P Build/NRD90M             1       0         0.0
  1030                            rv:54.0             1       0         0.0
  1039               LGMS550 Build/NRD90U             1       0         0.0
  1039      SAMSUNG-SM-G935A Build/NRD90M             1       0         0.0
  1045        RNE-L03 Build/HUAWEIRNE-L03             1       1         1.0
  1047              SM-G935T Build/NRD90M             1       0         0.0
  1047                  Z981 Build/MMB29M             3       3         1.0
  1054              SM-N950U Build/NMF26X             1       0         0.0
  1058 HUAWEI VNS-L23 Build/HUAWEIVNS-L23             4       0         0.0

In [32]:
G = nx.Graph()

for _, row in edge_stats.iterrows():

    card_node = f"card_{int(row['card1'])}"
    device_node = f"device_{row['DeviceInfo']}"

    G.add_node(
        card_node,
        node_type="card"
    )

    G.add_node(
        device_node,
        node_type="device"
    )

    G.add_edge(
        card_node,
        device_node,
        transactions=int(row["transactions"]),
        frauds=int(row["frauds"]),
        fraud_rate=float(row["fraud_rate"])
    )

print("Nodes:", G.number_of_nodes())
print("Edges:", G.number_of_edges())

Nodes: 3904
Edges: 12785

In [34]:
card_cols = [
    "card1", "card2", "card3",
    "card4", "card5", "card6"
]

card_results = []

for col in card_cols:

    cols_needed = ["TransactionID", "isFraud", "card1"]

    if col != "card1":
        cols_needed.append(col)

    temp = df[cols_needed].dropna(subset=[col])

    grouped = (
        temp.groupby(col)
        .agg(
            transactions=("TransactionID", "size"),
            unique_card1=("card1", "nunique"),
            frauds=("isFraud", "sum")
        )
    )

    card_results.append({
        "feature": col,
        "rows": len(temp),
        "unique_values": temp[col].nunique(),
        "values_2plus_card1": (
            (grouped["unique_card1"] >= 2).sum()
        ),
        "values_5plus_card1": (
            (grouped["unique_card1"] >= 5).sum()
        ),
        "median_card1_per_value": (
            grouped["unique_card1"].median()
        ),
        "p90_card1_per_value": (
            grouped["unique_card1"].quantile(.90)
        ),
        "max_card1_per_value": (
            grouped["unique_card1"].max()
        )
    })

card_screen = pd.DataFrame(card_results)

print(card_screen.to_string(index=False))

feature   rows  unique_values  values_2plus_card1  values_5plus_card1  median_card1_per_value  p90_card1_per_value  max_card1_per_value
  card1 590540          13553                   0                   0                     1.0                  1.0                    1
  card2 581607            500                 443                 213                     4.0                 21.1                 5392
  card3 588975            114                  86                  58                     5.0                 56.7                11245
  card4 588963              4                   4                   4                  2935.0               6721.7                 7646
  card5 586281            119                  70                  48                     2.0                119.4                 5863
  card6 588969              4                   4                   2                  2721.5               7372.0                 8200

In [35]:
card_combinations = [
    ["card1"],
    ["card1", "card2"],
    ["card1", "card2", "card3"],
    ["card1", "card2", "card3", "card4"],
    ["card1", "card2", "card3", "card4", "card5"],
    ["card1", "card2", "card3", "card4", "card5", "card6"]
]

for cols in card_combinations:

    temp = df[cols].dropna()

    temp["card_profile"] = (
        temp.astype(str).agg("|".join, axis=1)
    )

    counts = temp["card_profile"].value_counts()

    print(
        f"{'+'.join(cols):35s}",
        f"profiles={counts.size:7d}",
        f"repeated={sum(counts >= 2):7d}",
        f"10plus={sum(counts >= 10):7d}",
        f"max={counts.max():7d}"
    )

card1                               profiles=  13553 repeated=  10109 10plus=   4298 max=  14932
card1+card2                         profiles=  13490 repeated=  10061 10plus=   4267 max=  14891
card1+card2+card3                   profiles=  13497 repeated=  10066 10plus=   4268 max=  14891
card1+card2+card3+card4             profiles=  13488 repeated=  10065 10plus=   4268 max=  14891
card1+card2+card3+card4+card5       profiles=  13649 repeated=  10182 10plus=   4313 max=  14112
card1+card2+card3+card4+card5+card6 profiles=  13691 repeated=  10206 10plus=   4317 max=  14112

In [36]:
import pandas as pd
import numpy as np

# --------------------------------------------------
# Candidate entity features
# --------------------------------------------------

candidate_features = [
    "card2", "card3", "card4", "card5", "card6",
    "DeviceInfo", "DeviceType",
    "addr1", "addr2",
    "P_emaildomain", "R_emaildomain"
]

candidate_features += [
    f"id_{i:02d}" for i in range(1, 39)
]

# Keep only columns that actually exist
candidate_features = [
    c for c in candidate_features if c in df.columns
]


# --------------------------------------------------
# Measure how much each feature connects cards
# --------------------------------------------------

results = []

for feature in candidate_features:

    temp = df[["card1", feature]].dropna()

    # Number of unique cards connected to each value
    value_card_counts = (
        temp.groupby(feature)["card1"]
        .nunique()
    )

    results.append({
        "feature": feature,
        "unique_values": temp[feature].nunique(),

        # How many values connect >= 2 cards?
        "multi_card_values":
            (value_card_counts >= 2).sum(),

        # How many values connect >= 5 cards?
        "5plus_card_values":
            (value_card_counts >= 5).sum(),

        # Typical number of cards connected by a value
        "median_cards":
            value_card_counts.median(),

        # 90th percentile
        "p90_cards":
            value_card_counts.quantile(0.90),

        # Largest connected group
        "max_cards":
            value_card_counts.max()
    })

entity_connectivity = (
    pd.DataFrame(results)
    .sort_values(
        "5plus_card_values",
        ascending=False
    )
)

print(entity_connectivity.to_string(index=False))

      feature  unique_values  multi_card_values  5plus_card_values  median_cards  p90_cards  max_cards
   DeviceInfo           1786               1237                659           3.0       19.0       4846
        id_19            522                469                368           9.0       86.9       2898
        card2            500                443                213           4.0       21.1       5392
        id_20            394                270                161           3.0      210.5       1616
        id_11            365                265                157           3.0       30.6       8165
        addr1            332                184                118           2.0      463.3       2006
        id_31            130                114                106          40.0      802.6       3137
        id_33            260                154                100           2.0      116.0       3058
        id_06            101                 98                 91          59.0      487.0       6909
        id_08             94                 88                 75          26.0       69.9        230
        id_05             93                 85                 73          33.0      488.8       6870
        id_30             75                 74                 72         124.0      677.4       3248
        id_21            490                207                 71           1.0        7.1        743
        id_25            341                224                 71           2.0        9.0        732
        id_02         115655              20407                 63           1.0        2.0          6
        id_07             84                 73                 60          16.5      104.0        210
P_emaildomain             59                 59                 58         106.0     1170.4       8933
R_emaildomain             60                 60                 58          51.5      481.6       5093
        card3            114                 86                 58           5.0       56.7      11245
        id_17            104                 86                 54           5.0       42.1       6476
        card5            119                 70                 48           2.0      119.4       5863
        id_26             95                 71                 45           4.0       60.6        302
        id_01             77                 50                 36           3.0      437.4       6355
        id_13             54                 44                 34          15.5      739.5       5312
        id_10             62                 47                 32           6.0       76.0       5936
        id_09             46                 38                 24           5.5      153.5       5809
        addr2             74                 46                 23           2.0       16.0      11538
        id_14             25                 22                 21          31.0     1431.0       4229
        id_03             24                 22                 18           9.5      283.0       5468
        id_04             15                 15                 14          21.0       63.0       5566
        id_18             18                 14                 11          30.5     1718.9       3410
        id_24             12                 11                  8           9.0      537.9        814
        card4              4                  4                  4        2935.0     6721.7       7646
        id_32              4                  4                  4        1801.0     4892.0       5465
        id_22             25                 17                  4           3.0       19.8       1218
        id_34              4                  4                  3        1570.5     4963.1       5837
        id_23              3                  3                  3         403.0      869.4        986
        id_15              3                  3                  3        5690.0     6218.0       6350
   DeviceType              2                  2                  2        5845.0     6536.2       6709
        card6              4                  4                  2        2721.5     7372.0       8200
        id_12              2                  2                  2        5514.5     7728.5       8282
        id_16              2                  2                  2        6016.0     6344.8       6427
        id_29              2                  2                  2        6242.0     6398.0       6437
        id_27              2                  2                  2         656.5     1175.3       1305
        id_28              2                  2                  2        6237.5     6332.3       6356
        id_35              2                  2                  2        4756.0     6224.0       6591
        id_36              2                  2                  2        4860.5     7530.5       8198
        id_37              2                  2                  2        5741.0     7025.8       7347
        id_38              2                  2                  2        5844.0     6071.2       6128

In [38]:
specificity_results = []

for feature in candidate_features:

    temp = df[["card1", feature]].dropna()

    counts = (
        temp.groupby(feature)["card1"]
        .nunique()
    )

    specificity_results.append({
        "feature": feature,

        "unique_values": len(counts),

        # Fraction of values shared by multiple cards
        "multi_card_fraction":
            (counts >= 2).mean(),

        # Fraction of values shared by >= 5 cards
        "5plus_fraction":
            (counts >= 5).mean(),

        # Fraction of values that are extremely common
        "100plus_fraction":
            (counts >= 100).mean(),

        "max_cards": counts.max(),

        # Useful summary of typical sharing
        "median_cards": counts.median()
    })

specificity = (
    pd.DataFrame(specificity_results)
    .sort_values(
        "100plus_fraction",
        ascending=True
    )
)

print(specificity.to_string(index=False))

      feature  unique_values  multi_card_fraction  5plus_fraction  100plus_fraction  max_cards  median_cards
        id_02         115655             0.176447        0.000545          0.000000          6           1.0
        id_21            490             0.422449        0.144898          0.004082        743           1.0
   DeviceInfo           1786             0.692609        0.368981          0.008399       4846           3.0
        id_25            341             0.656891        0.208211          0.008798        732           2.0
        id_11            365             0.726027        0.430137          0.030137       8165           3.0
        card2            500             0.886000        0.426000          0.036000       5392           4.0
        id_17            104             0.826923        0.519231          0.038462       6476           5.0
        id_22             25             0.680000        0.160000          0.040000       1218           3.0
        addr2             74             0.621622        0.310811          0.040541      11538           2.0
        card3            114             0.754386        0.508772          0.061404      11245           5.0
        id_08             94             0.936170        0.797872          0.063830        230          26.0
        id_10             62             0.758065        0.516129          0.064516       5936           6.0
        id_04             15             1.000000        0.933333          0.066667       5566          21.0
        id_26             95             0.747368        0.473684          0.084211        302           4.0
        id_19            522             0.898467        0.704981          0.093870       2898           9.0
        id_33            260             0.592308        0.384615          0.115385       3058           2.0
        id_07             84             0.869048        0.714286          0.119048        210          16.5
        card5            119             0.588235        0.403361          0.126050       5863           2.0
        id_09             46             0.826087        0.521739          0.130435       5809           5.5
        id_20            394             0.685279        0.408629          0.149746       1616           3.0
        addr1            332             0.554217        0.355422          0.159639       2006           2.0
        id_03             24             0.916667        0.750000          0.166667       5468           9.5
        id_01             77             0.649351        0.467532          0.194805       6355           3.0
        id_14             25             0.880000        0.840000          0.240000       4229          31.0
        id_24             12             0.916667        0.666667          0.250000        814           9.0
        id_18             18             0.777778        0.611111          0.277778       3410          30.5
        id_31            130             0.876923        0.815385          0.307692       3137          40.0
R_emaildomain             60             1.000000        0.966667          0.333333       5093          51.5
        id_13             54             0.814815        0.629630          0.351852       5312          15.5
        id_05             93             0.913978        0.784946          0.387097       6870          33.0
        id_06            101             0.970297        0.900990          0.396040       6909          59.0
        card6              4             1.000000        0.500000          0.500000       8200        2721.5
        id_27              2             1.000000        1.000000          0.500000       1305         656.5
        id_32              4             1.000000        1.000000          0.500000       5465        1801.0
P_emaildomain             59             1.000000        0.983051          0.525424       8933         106.0
        id_30             75             0.986667        0.960000          0.560000       3248         124.0
        card4              4             1.000000        1.000000          0.750000       7646        2935.0
        id_34              4             1.000000        0.750000          0.750000       5837        1570.5
        id_12              2             1.000000        1.000000          1.000000       8282        5514.5
   DeviceType              2             1.000000        1.000000          1.000000       6709        5845.0
        id_15              3             1.000000        1.000000          1.000000       6350        5690.0
        id_16              2             1.000000        1.000000          1.000000       6427        6016.0
        id_23              3             1.000000        1.000000          1.000000        986         403.0
        id_28              2             1.000000        1.000000          1.000000       6356        6237.5
        id_29              2             1.000000        1.000000          1.000000       6437        6242.0
        id_35              2             1.000000        1.000000          1.000000       6591        4756.0
        id_36              2             1.000000        1.000000          1.000000       8198        4860.5
        id_37              2             1.000000        1.000000          1.000000       7347        5741.0
        id_38              2             1.000000        1.000000          1.000000       6128        5844.0

In [39]:
# Sort chronologically
df_sorted = df.sort_values("TransactionDT").copy()

split_idx = int(len(df_sorted) * 0.80)

train_df = df_sorted.iloc[:split_idx].copy()
test_df  = df_sorted.iloc[split_idx:].copy()

print("Train:", train_df.shape)
print("Test :", test_df.shape)

print(
    "Train fraud rate:",
    train_df["isFraud"].mean()
)

print(
    "Test fraud rate:",
    test_df["isFraud"].mean()
)

Train: (472432, 55)
Test : (118108, 55)
Train fraud rate: 0.03513521522674162
Test fraud rate: 0.034409184813899145

In [40]:
fraud_signal_results = []

for feature in candidate_features:

    train_temp = train_df[
        ["card1", feature, "isFraud"]
    ].dropna()

    stats = (
        train_temp
        .groupby(feature)
        .agg(
            transactions=("isFraud", "size"),
            frauds=("isFraud", "sum")
        )
    )

    stats["fraud_rate"] = (
        stats["frauds"] /
        stats["transactions"]
    )

    # Only reasonably observed entities
    mature = stats[
        stats["transactions"] >= 5
    ]

    fraud_signal_results.append({
        "feature": feature,

        "entities_5plus_tx":
            len(mature),

        "median_fraud_rate":
            mature["fraud_rate"].median()
            if len(mature) else np.nan,

        "p90_fraud_rate":
            mature["fraud_rate"].quantile(.90)
            if len(mature) else np.nan,

        "entities_50pct_plus":
            (mature["fraud_rate"] >= 0.50).sum(),

        "entities_80pct_plus":
            (mature["fraud_rate"] >= 0.80).sum()
    })

fraud_signal = pd.DataFrame(fraud_signal_results)

print(
    fraud_signal
    .sort_values(
        "entities_80pct_plus",
        ascending=False
    )
    .to_string(index=False)
)

      feature  entities_5plus_tx  median_fraud_rate  p90_fraud_rate  entities_50pct_plus  entities_80pct_plus
   DeviceInfo                771           0.000000        0.428571                   67                   31
        id_25                 90           0.000000        0.600000                   11                    5
        id_20                197           0.005051        0.170583                    8                    3
        id_13                 35           0.071709        0.628000                    5                    3
        id_33                 95           0.013158        0.342286                    8                    3
        id_31                 95           0.087079        0.303320                    6                    2
        id_21                 86           0.000000        0.373077                    8                    2
        id_19                386           0.000000        0.150303                   14                    2
        id_03                 18           0.263768        0.698901                    4                    1
        id_17                 63           0.000000        0.306667                    4                    1
        addr2                 28           0.000000        0.141915                    2                    1
R_emaildomain                 60           0.000000        0.115509                    1                    1
        id_26                 47           0.022989        0.219196                    1                    1
        card6                  4           0.011985        0.054287                    0                    0
        card5                 74           0.018774        0.082839                    1                    0
        card3                 71           0.012500        0.153846                    0                    0
        card2                500           0.008753        0.082451                    0                    0
        id_06                 92           0.075135        0.135321                    1                    0
        id_05                 73           0.090100        0.179853                    1                    0
        id_04                 14           0.208696        0.512963                    3                    0
        id_02                 24           0.000000        0.200000                    0                    0
P_emaildomain                 59           0.014706        0.055006                    0                    0
        id_01                 34           0.120665        0.349016                    2                    0
   DeviceType                  2           0.080724        0.095376                    0                    0
        addr1                131           0.020106        0.166667                    2                    0
        card4                  4           0.034815        0.062511                    0                    0
        id_12                  2           0.070393        0.076002                    0                    0
        id_11                146           0.000000        0.111111                    0                    0
        id_10                 34           0.000000        0.157609                    0                    0
        id_14                 21           0.077670        0.396226                    1                    0
        id_07                 60           0.072401        0.242857                    1                    0
        id_09                 23           0.142857        0.355897                    0                    0
        id_08                 74           0.057581        0.193176                    1                    0
        id_22                 10           0.000000        0.207037                    0                    0
        id_15                  3           0.089946        0.099559                    0                    0
        id_16                  2           0.075527        0.098596                    0                    0
        id_18                 12           0.058799        0.188082                    0                    0
        id_27                  2           0.039193        0.070547                    0                    0
        id_28                  2           0.075074        0.094604                    0                    0
        id_24                  6           0.078011        0.342857                    0                    0
        id_23                  3           0.069547        0.109552                    0                    0
        id_30                 70           0.041978        0.122336                    0                    0
        id_29                  2           0.075517        0.096220                    0                    0
        id_32                  4           0.157335        0.495000                    1                    0
        id_34                  3           0.038105        0.058352                    0                    0
        id_35                  2           0.081311        0.111205                    0                    0
        id_36                  2           0.055412        0.074417                    0                    0
        id_37                  2           0.072000        0.078688                    0                    0
        id_38                  2           0.077131        0.090614                    0                    0

In [41]:
graph_candidates = [
    "DeviceInfo",
    "id_19",
    "id_20",
    "id_31",
    "id_06",
    "id_30",
    "id_33",
    "id_05",
    "id_08",
    "id_17",
    "id_21",
    "addr1",
    "addr2",
    "card2",
    "card3",
    "card5"
]

graph_candidates = [
    c for c in graph_candidates
    if c in df.columns
]

print(graph_candidates)

['DeviceInfo', 'id_19', 'id_20', 'id_31', 'id_06', 'id_30', 'id_33', 'id_05', 'id_08', 'id_17', 'id_21', 'addr1', 'addr2', 'card2', 'card3', 'card5']

In [42]:
from itertools import combinations
from collections import defaultdict
import pandas as pd
import numpy as np

MAX_CARDS_PER_VALUE = 50

feature_edges = {}

for feature in graph_candidates:

    temp = (
        df[["card1", feature]]
        .dropna()
        .drop_duplicates()
    )

    # Group cards belonging to each entity value
    groups = temp.groupby(feature)["card1"]

    edges = set()

    for value, cards in groups:

        cards = list(cards)

        # Avoid huge generic hubs
        if len(cards) > MAX_CARDS_PER_VALUE:
            cards = cards[:MAX_CARDS_PER_VALUE]

        if len(cards) < 2:
            continue

        # Every pair of cards sharing this entity
        for a, b in combinations(sorted(cards), 2):
            edges.add((a, b))

    feature_edges[feature] = edges

    print(
        f"{feature:12s} -> "
        f"{len(edges):,} sampled card-pair edges"
    )

DeviceInfo   -> 63,385 sampled card-pair edges
id_19        -> 98,669 sampled card-pair edges
id_20        -> 81,651 sampled card-pair edges
id_31        -> 64,632 sampled card-pair edges
id_06        -> 51,630 sampled card-pair edges
id_30        -> 57,549 sampled card-pair edges
id_33        -> 48,454 sampled card-pair edges
id_05        -> 44,542 sampled card-pair edges
id_08        -> 39,285 sampled card-pair edges
id_17        -> 18,749 sampled card-pair edges
id_21        -> 12,361 sampled card-pair edges
addr1        -> 67,837 sampled card-pair edges
addr2        -> 6,114 sampled card-pair edges
card2        -> 53,003 sampled card-pair edges
card3        -> 26,177 sampled card-pair edges
card5        -> 33,673 sampled card-pair edges

In [43]:
features = list(feature_edges.keys())

redundancy_rows = []

for i in range(len(features)):

    for j in range(i + 1, len(features)):

        f1 = features[i]
        f2 = features[j]

        e1 = feature_edges[f1]
        e2 = feature_edges[f2]

        if not e1 or not e2:
            continue

        intersection = len(e1 & e2)
        union = len(e1 | e2)

        jaccard = intersection / union if union else 0

        redundancy_rows.append({
            "feature_1": f1,
            "feature_2": f2,
            "shared_edges": intersection,
            "jaccard": jaccard
        })

redundancy_df = (
    pd.DataFrame(redundancy_rows)
    .sort_values("jaccard", ascending=False)
)

print(
    redundancy_df
    .head(30)
    .to_string(index=False)
)

 feature_1 feature_2  shared_edges  jaccard
     id_19     id_20         25253 0.162852
DeviceInfo     id_31         17130 0.154482
     id_06     id_05         12486 0.149201
     id_17     card3          5480 0.138924
     id_30     id_33         11978 0.127392
     id_20     id_17         11182 0.125333
     id_31     id_05         11472 0.117418
     addr2     card3          3379 0.116872
     id_31     id_06         12104 0.116208
     id_20     addr1         14870 0.110461
DeviceInfo     id_05         10466 0.107387
DeviceInfo     id_19         15478 0.105597
DeviceInfo     id_20         13290 0.100876
     id_19     id_30         14136 0.099492
     id_19     id_31         14643 0.098501
     id_19     id_05         12835 0.098446
DeviceInfo     id_06         10092 0.096185
     id_06     id_08          7907 0.095256
     id_19     id_33         12415 0.092162
     id_20     id_31         12168 0.090728
     id_19     id_06         12365 0.089644
     id_05     id_08          6889 0.089540
     id_31     id_30         10039 0.089520
     id_20     id_05         10067 0.086690
DeviceInfo     id_30          9584 0.086071
     id_19     addr1         13038 0.084956
     id_08     id_21          3922 0.082181
     id_20     id_30         10470 0.081333
DeviceInfo     id_33          8191 0.079027
     id_30     id_05          7454 0.078764

In [44]:
card_stats = (
    train_df
    .groupby("card1")["isFraud"]
    .agg(
        card_transactions="size",
        card_frauds="sum"
    )
)

card_stats["card_fraud_rate"] = (
    card_stats["card_frauds"] /
    card_stats["card_transactions"]
)

print(card_stats.head())

       card_transactions  card_frauds  card_fraud_rate
card1
1000                   1            0              0.0
1001                   3            0              0.0
1004                   3            0              0.0
1005                   1            0              0.0
1006                   3            0              0.0

In [45]:
edge_quality_rows = []

BASELINE = train_df["isFraud"].mean()

for feature in graph_candidates:

    temp = train_df[
        ["card1", feature]
    ].dropna()

    # Entity-level transaction count
    entity_tx = (
        temp.groupby(feature)
        .size()
        .rename("entity_transactions")
    )

    # Keep reasonably observed entities
    mature_entities = entity_tx[
        entity_tx >= 5
    ].index

    temp = temp[
        temp[feature].isin(mature_entities)
    ]

    # Attach card fraud statistics
    temp = temp.join(
        card_stats["card_fraud_rate"],
        on="card1"
    )

    # Entity -> unique cards
    entity_card_stats = (
        temp
        .drop_duplicates([feature, "card1"])
        .groupby(feature)
        .agg(
            unique_cards=("card1", "nunique"),
            mean_card_fraud_rate=(
                "card_fraud_rate", "mean"
            ),
            median_card_fraud_rate=(
                "card_fraud_rate", "median"
            )
        )
    )

    if len(entity_card_stats) == 0:
        continue

    # How many entities have unusually
    # high fraud-connected cards?
    high_risk = (
        entity_card_stats[
            entity_card_stats["mean_card_fraud_rate"]
            >= BASELINE * 3
        ]
    )

    edge_quality_rows.append({
        "feature": feature,

        "mature_entities":
            len(entity_card_stats),

        "median_cards_per_entity":
            entity_card_stats["unique_cards"].median(),

        "median_card_fraud_rate":
            entity_card_stats[
                "mean_card_fraud_rate"
            ].median(),

        "p90_card_fraud_rate":
            entity_card_stats[
                "mean_card_fraud_rate"
            ].quantile(.90),

        "high_risk_entity_pct":
            len(high_risk) /
            len(entity_card_stats),

        "max_card_fraud_rate":
            entity_card_stats[
                "mean_card_fraud_rate"
            ].max()
    })

edge_quality = (
    pd.DataFrame(edge_quality_rows)
    .sort_values(
        "high_risk_entity_pct",
        ascending=False
    )
)

print(
    edge_quality.to_string(index=False)
)

   feature  mature_entities  median_cards_per_entity  median_card_fraud_rate  p90_card_fraud_rate  high_risk_entity_pct  max_card_fraud_rate
DeviceInfo              771                      7.0                0.088140             0.157195              0.398184             0.484737
     addr1              131                     26.0                0.030797             0.160916              0.251908             0.236138
     addr2               28                      6.5                0.015923             0.150000              0.214286             0.536111
     card3               71                     13.0                0.019290             0.190476              0.211268             0.500000
     id_05               73                     92.0                0.049263             0.121129              0.178082             0.137226
     id_31               95                     55.0                0.068556             0.134623              0.168421             0.450000
     id_20              197                     16.0                0.029700             0.136071              0.162437             1.000000
     id_21               86                      7.5                0.039405             0.117095              0.151163             0.305329
     id_17               63                      9.0                0.020677             0.132748              0.142857             1.000000
     card5               74                     12.5                0.022389             0.109993              0.121622             0.333333
     id_19              386                     12.0                0.034234             0.109153              0.108808             0.277273
     card2              500                      4.0                0.004389             0.092879              0.096000             0.507042
     id_33               95                     26.0                0.033251             0.068774              0.073684             0.410397
     id_08               74                     32.0                0.039882             0.072783              0.013514             0.127909
     id_06               92                     61.5                0.058487             0.082100              0.000000             0.092967
     id_30               70                    119.5                0.031817             0.045814              0.000000             0.081132